package advent.advent2024

import utils.Point

private var result = 0

fun main() {
    result = test(
        """
            .M.S......
            ..A..MSMS.
            .M.S.MAA..
            ..A.ASMSM.
            .M.S.M....
            ..........
            S.S.S.S.S.
            .A.A.A.A..
            M.M.M.M.M.
            ..........
    """.trimIndent()
    )
    check(9, result)

    result = test(
        """
            XMASAXMASXXMMAMAXAXXXMSASXSXSXMAMMAMXMASASXMXMASMSMSSMMSXMASXMSMXMASMMSSMMMSMMAMMSMMMMMSXMAXMSMMMMMSAXAXXXMASAMXXSXMXSSSMSMSXMAMXXXSAXSMSAMX
            MSMMMMSMXMXSSSSSSMSMSMSASAAXXASAXXMAXSMSAMMSAMSXAAAAXSAMXMASXMXMASAMXXAAAXMAMMAAMAMXAASAMMMSAMXMAASMSXMSMSMXMASMXMASXMAAXAAAXXSSSMMAMMXAXSXX
            AAAAAAAMMSAAMAAAXAAAAAMMMMMXMXMASXMSASXMAMAMASAMSMMMXMXSAMXSXMASXSAMXMSSMMSASXXSSMMSAMMASAAAAXXXSMSAAMXAAMSXSAMASAAMAMAMSMSMSMAAASAAXAMXMMMS
            SSSMMSSSSMSSMMMMMSMXMMMAAXXAXAMXMXAMASMSMMMSMMMXASAMXSMSXSAMAXAMAMASAMXAXXMAMXAAMXXMXMMAMMSSSMXXXAMXMAMMSMAXMASXXMASMMAXAAAXAAMMMMSXXSAMXAAA
            XMAXMXXMAAAXXXAMXXSMMMSMMSAMXMMMMMXMXMAAMAASAMXSAXXMAXAMXMMSSMSSSSMMASXMMMMAMSSMSMMAAXMASXAAAAASMMMSXSXAXMAMSAMXSSMSXMAMMXMSMSSXSAMXAAXXSMSS
            XMASMMASMMMSSSMMSAMXSAAAAAXMAMASAMASXMSMSMXSASXXSMSMSSSSXXAAAAAAXAASAMASXXMMXAAXXAMMASAMXMMMMSMXAAXMAMMMMMXMMASAAAXMASXMSMAMXAAXMASAMXMMAAAM
            XAXAAAAXAXAAAAMSMAMAMSSMMSMSMSASASASAXAAXMASAMMAMSXMAAAXMMMSMMMMSSMMXSXMMAMSMMSMSXMMAAAMMXSAAAMSMMSMAMAMAMASXMMMSMMMAMAAAAAMMMSMMAMMSAMXMMMS
            MSXSMMXSXMMSSMMMSXMXMAMAAAXXAMAMAMXXAMXSXXAMMAMAMSXMMMMMMMXAXXMAXMASXMMASAMAXXAMXAXMXSAMMASMSXMXMAXXAXAMAMXSAMXXAXXMMMMMMSMSAXMAMSSXSAMXSAMA
            AAAMXSASASMAXAAAMXSSMMSMMSSMSMSMSSXMXAMMMMXSSXMSSMAXAAAAAXXMSMXXXXAXAASMSASASMSXSSMMMMXXMASXMXSMMXSXXMMXMMAMAMXSAMXSSXMAAAXSMSMSAAAXSAMASASM
            SXXMAMASAMMMSSMMSAXAMXAMMXMAAAAXXAASMXSASXAMAMXMAMAMXSSSXSAXAXMMMMMSSMMASXMXSAAASMSAAMXSMASAMAAASXMXSAMAXMSMSXMASXMASAMMMSXXXAAMMXMAXAMXSAMX
            MMMMXMXMXMXXAMXAMXXSMSMXSAMSMSMXMXMMAAMAMMMSAMXMAXMXAMXAASMMMSAAAAAXAXMXMASXMMMSMAXMMSAXMASAMXSXMAAASAMMSAMAAXXAXXXAXXMAXMMXSXXMXSMXSAMAMAMS
            XAAMAMAMSAMAAAMSSSMAAXAAMXMAXXXXSMMMMMMSMAXXXMMSSMMSMMMMMMAAAXXMXMXSMMMXXMMXMXMAMMMXAMMXSASAMMMMSMMMXAMXAAMAMMMSMSMMMAXAXAMXXMSMXXAXMASMSAMX
            XSMSAXASAASXMMAMAASAMXXMSMSMSXMAXAAMAMAMXMSSXSAAAXAAXAAMXSSMSSXSASXSXAMAMXSXMASXSMSMASAAMAMAMAXAAMAXXAMAMAMAXXXAAMASAMMMSMSMMSAMXMXMSAMXSXSA
            MMASMSMSMMAAAASMMMMMXMASAAAAMMMASXMSXMASAMAAASMSSMSSSMMAMXXAXAMXAXAMXSMXSAAASASAAAMSAMMMSASMMSMSMSASMSMMMAMMXXSAMSAMAMAXAMAAMSASXSAAMASAMXXM
            MMAMAAAXAMSSMMXASXSXASXMMSMXMAXXAXXAAXASAMMMMMXXAAXXAXAAMXSXMXMMSMSAMXAAAMSMMAMAMMMMXSAMMXMXAAXMXMMSXAAAXMMMAASXMMASASMSSSSSMMAMASMXSXMASMMM
            XMSMSMSMSAAXXASXMASMMMAXMAXMSMSXAXMMSMASAMSSXMSMSMMSAMSSMAMAMXMAMMAAAMMMXMAXASMAXAXMMSMSMSXMXMXMAMAMXSMMXSAMMXSAMMMMAMAAAAMAMMSMAMAASAXAMAAM
            ASXAAMAAXMSMSAMXMXMAMMSMMASXAAAMSMAAAMMMAMAAAAMAAAXXAXAMMAMAMAMASASMSXAXXXXXSASXSSMMAMXMASMMMXXSMMSMMXXAASXMMAMAMXSMSMMMMMXAMXMMAMMMXAMSSSMS
            MMMSMSMXMXAAAAMXMASXMAXAMAMMMMMAAASMSXXASMSSMMXSSMMMSMMMSASASXMASAMMMMXAMXMMXMAXMAXSSSSMAMAASMMXAAMASMMMMSXAMASMMAMAMMXXXXMSSMXSSMMSMSAMAAXA
            MAAMAXMAMSAXSAMASMSAMAMAMXXAXMSSMXMAMASMMAMXMXMAAAAAXAAASMSXSXMXMMMASASXXSMAXXMSMMMSAAXMSMSMSAMSMMSXMAXMAXMMXMAASXMAMXXXXXAXAMXAAMASAXSXXMAS
            SASMXMASAASAMXXASXMMMMSSMMXSMMAAXSMASAXXMXMXMAMXSXMSXMAXSXSASXSAAAXMMAXMASXSAXXAAXXMMMMXAAAAXMMAAAXAMSSSSSSMAMSXMASMSASMMMMSSMMSMMAMXMMXMXMX
            AAXMXMAMXAMMSSSXXXMSSMAMAMAXAMMSAMMAMMMXXASMSASMMXSAMXMASAMAMASMSMSSMXMSXSMXAXMSMMXXAAASMSMSMSSSSMSSMXMAXAAAXMXASASASMAAAMXAXAAXXMAXAXMASAMX
            XXAAAMXSXSXAAAAMMMXAAMXSAMMSAMXMAXMASMAXSASASASAMXMAMXSASMMMMAMXMASAAMAMAMXMXMAMASXSMSMMAMAAXXMAXAAMAXMXMSMMXSXXMASAMXSXMMMMSMMXMSSSSXSXXAXX
            MMMSMSXSAXMMMSMAAMMMSMAMXMASAMXSAMXMXMAMMXMXMAMXMASAMXAAMXMAMAMXMMMMSXMMAMMSAXXSASAAXMXMAMMMXSMMMMMXSMXMAMAMASAMMAMAMMXXMXAMAMAXMAXXAASMSSMM
            ASMMAMAMXMAAMXXSMMXMAMMSSXASAMXMXMAXMMXSMMMAMXMASXSMSAMXSXSASAXXXAAXMAXSAMASASAMXMMMMSASMSASMXASXXSAAMXXMXAMAMXXMAMXMAXMAMMXASXSMMSMSMSAAXAM
            MAASAMSMSSSMSXXXMAAMASMAMMAMXMAMAMMSAMXMAXSASMSAMMMXMXXXAASASAMSSSMSMSMSAMAMSMXSAMXMMSAMASASXMSMAAMSMMMMMSAMXSSSSMSMMMSSMXSXMSMXAXXAMAMMMSSM
            XMXMAMXAAAXMAMXXMXMSAXMAMXMASMSSSSXSXMASMMMXMAAAAASASMSMMXMMMMMAAAASAMMSMMMSXXAXASMSAMAMMMXMASAMMMMMXMMSAAXXASAAMAAXAAAAMASAMXXMXMXSMAMMXAXM
            MXXSXMMMMMMMASMASAMMXMSMSXAXXAXAAXAMAXASASMMMSSMXASASAAMXXAXAAXMMMMMAMASXXXAMMMSMMAMMSAMAMASMMMXAAAXXXAAAMSMMSMMMSMSMMSXMASAMASXMXAAXAXXMASM
            SSMMAMXMAMAMAXXAMXSXMAAASMMMMMMMMMMSSMMSAMAAAAAMSMMMMXMSSSMMMXSAMXXXAMAXMAMXMSAAAMMMASASXSASXXASMSSSXMMSMMXAAXAXAAXAXMMXMXSAMAMAMMMSSSSXSAMX
            AMAMMXSXMASXMSMXSXMXAMMMMAAAAMMMMXXAAAASMMSMMSSMAMXSXMXSAAXXXAMXMASMXMASXMMAMMSMSMSMMSAMXMAXXAXMAXMAAXXMXMXSXSMMSMSSSXSASXSXMAXAMAXAAMSAMXSX
            MSAMSMSASAMAMMMAAAMAXXAAMSMSXXAAAMMSSMMMAAXMXXAXMSAMASMMSMMMMMSXMAMAAMMMAAMMSAAXAMXAXMXMSMAMSMMMMMMXMMMMMSAMMSAAAAAXMAMMMAMASXSSSSSMSXSXSASX
            XMAMSAMXMASXMASASMMAXSSXMAAAMSSMXAMAMXSXMMSSSSMMXMASAMAAXXAXAAMAMASMXSASXMMXMAXSMXSAMXSMMMXMAAAXSAXAMXAAAMAXAXMMMMMSSSXSMAMAMMXAAXXXAAMXMASX
            MSSMMMMXSXMASASAMASXXMAMSMMMMAXSMSAMXASAMAXXAAXAXSMMMSMMMSSSSMSAMASAASASAMXMXMXXXXSASASAAXAMSMMXSMSMXXXMXXXMMXAMXMAXAAAMSSSXSXMMMMMMMSMXMXMX
            MAMASAMXMASAMAXMMAMXAMSMMXXSMMSMXMAXMMSAMXSMXMMMXXAAASXMMXMAMAMMMAMMMMAMMMAMAMMMMMSAMASMMSSMXASMXMAXXMASMXMXSAMXSMSMMMSMAMMMMASAAAAAXAMAMAMX
            MMSAMAMAMMMSMAMSMSSSXXMASXMAAXMASXSMSXSMMXXMXAAXXXMMXMASMMMSMAMXXAXAMXMAMMXMASAAAAMXMAMAXMXAMAXMASASXSMXAASASMSXMAXSXXXMASAMSAMXSSSXSASMSASX
            SAMMSASMXXAXMXSXAXAXMASXMAMXAMXAMXMASAMMXMAXSSMSSMSMSSSMSAAAMAMXXXSSSXMASMMSASAMMSSXSAMMMMMSMMMSXSAXXAAMSMMAMXMAMXMXSXSSMMAMMMMXMAAASAAASAMX
            XAMXSASASMAXXMMMMMMMAXMAMXMASMMXSXMMMXMAAMSAMXXMASAAAMMASMSMSMSMMMMAAXMASAXAMXAXSXMAXMXXMAAXAAXMAMXMSMMMMAMMMSSMMSSMXMAAMMSMSASAMMMMMMMMMAMX
            SAMAMMMAMXMMSXMAAAXMMXMSMSXMXAMXXMXXXMASXSAAMASAMXMMMSMMMXAXAAAMAAXMMXMMSMMXMMMMXAMSMMMSSMSSSMSSMXAXXAMMSAMXXAAAAAXAAASXMAAASASXSAMXXXSMMXMX
            SXMMASMSMAMAXASMSSSSXMMAAXAMXAXASASAXMXXMAXMMASMXSXXASAMSMMSMMMSMMSXAXSXSXMSMSSSSXMAAAAMAAAAAMAAXSAMMXSASXSAMSSMMMMMXXXXMMMXMMMASMMMXMXMASMM
            SAMXXMAAXXMAMMMAAAAAASXSMMAMXMMMMXMMMMAASASXSXXMASMMMMAMSAMXAXMMMMMMMMSAMXXSAAXAAASXSMSMMMMSMMSSMMXMAXMASAMMAXXXXSASMXSXSAMAMAMAMAASASAMXSAA
            SMMSXMMMXSXSXXMMMMMMMMAAMSSMAXAXSASASMAXSAMAAMXMAXAASXMMSXMMMMAAAMAMXAMAMMXMMMSMSMMXMXMXSXXXXXXAAXXMSSMAMMMAXXMMMMASAASASASXSXMXSSMSASAMAMMM
            MAAMMMAXMSAMSXXMAMSSSMMMMAASXMMMSASASMMMMAMXMXSMMMMMSAAASMSXSAMSMSXSMMSMAAAMAMXAAAXXSAMXMAMXMMSSMMXMMAMMSSMSMXAAMMMMMMMAXMMAMMMAXMASAMXXSSSS
            SMSSMSASXMAMAMXSASXAXAMXMSXSMXSAMXMMMASXSXMMXMSASAMASXMMMAXAXSXMXMAXMAAMMSXSASMSMSMMMMMAMMAAAAMAAXMXSMMXAMXAASMMSXXAXMMSMXMAMAMASMMMMSXMMAAA
            MXMAASXSXSAMMSASXSMSMMXSXMASAASXSMSXMASAMMSAAAMAMAMASXMSMSMSMMMXAMMMMSMSXMAMXXAAAAXXAXSASAMSSSSSSMSAMXSMXSMMMMAAMMSMSMAAAXXXMMXMXAAAASMMMMMM
            AASMMMXMASXSXMMSAMXMXSAMASAMMMSASAMXSXMMMASXMMXASXMAMAXMAXAAMXAXSASMAMASAXMSASMMMSASAXMASMXMAAAAXAMASAMMAMAXSXMAMXMAAMXSSSSMMSAMMSMMMSASXSAM
            SMSASMAMMMASAMAMAXAMMMASMMASXXMAMXMASAMXMMXXMAMMMMMSSXMMMMSMSMSMXAMAXMASAMMMMSXAAXAMXSMMMMAMMMMMMXSMMASMAMXXMAXMXSMSMSXXAAXAASAMAXXMXSMMAXMM
            MASAMMAXAXMSMMAMSSMMASMMXSXMMXMXMSMXSMMMMMMSMSXXAMAMAXMAMMAAAAMMMAMSXMXMXSXAMSMMMASMASMMASXMAXAXAXMAMXMMSSMXXMASAMMMAAXMMMMMMXXMAXAAAMXMMMSA
            MAMAMSMSMSAMXMASAAASXSAMASASXXSAAXMMMAAAAMAMAMXSXMASMMSSSSMXMSMMXAMMAMXXMAMASXAXAAMMXSASXMAXSSMMXMAMSASAMXMSAMXMASAMMMMAAMSMSMMMSSSMSSSXAAMX
            MMSXMAXAAAMAASXMMSMMAXAMASMMAXSMXASASXMSMXAMMMMAASASXXXAAMAASMMXSASMMMASMAXMMMMMMMSSMSAMXMMMMAAAXSAMSAMAMAMMASAAAMASMAASMSAAAAAAXXMAXXMXMXMM
            SAXMSMSMSMXSXSAMXXAMXSSMXMAMAMXMSASMSAAAASXSMAXMMMAXXMMMMMSMSAAXSMMAXMXAMXSXMASASAMAMMAMXASMSSMMXMAMMXMAMMXSAMXMMSXMMMXMXSMSMMMMSAMMMAAMSMSA
            MXMXAAXXAXXAMXASAMAMXXXAAMAXAAAAMAMMMMMMXMAAXXSMSASMMSAXXMXASMMXSASMSMSMXXMXSXSAMXMAMSMMSXAAAXMSSSMMMSSXASAMXSXMASMMXXMMAMXXMSSXSXMASXXXAAMX
            XMSSMSMSMSXXASMMMSSSMMSSMXMMSMMMXXSMSMASXMSMMMMXAAAAASAMXMMXMXMASAMAAAAMMAMXMMMXMMSMMSAMXXMMMMSAMAAXXAASMMAAAXAMASAMXXXMMMSXAXMAXMSXSXMMMSMS
            MMAMAMMXMXMXMMXXXAAAAXMXMASMMXSXMAXAAMAMMMMASAMAMXMMMSSXAXMSMSMAXAMSMSMSMXMAXAAAMAAMXSAMMAXSAMXMSSMMMAXMXSXMSSMMAMMMASXSXAXMMMMXMXMXMMSAMAAA
            AMASAMMAMAMXMMAMMSMSAMXSSMXAXASAMAMSMMASAAMSXSMSSMXMAXMSSSXAAAMSSMMAMAAXMAMMSMSSSSXMAMAMAAMSAMMXMAMXSSXAXMXXMAAAAXSMMAAMMMMAASMMSXMASAMASMSM
            MSXSASXXSASAXMASXXAMXSAMAMSMMASXMXXXAXMSMSXXAXSAMXAMSXMXMSXMSMSMAASXMMXMMASMAAAAAXAMSSMMSAMXAMAAXXMASMXMSMMMSAMXMMXAMMAMAAXSMSXAMXSSSMSMMXMX
            ASMSMMAXMASMXMXXAMXMAMXXAMAXMXMAMMMSSMMXAMMMMMMXSSMXXASMMSXMXMAMMMMAMSXXMAXXSMMMMMXMAAXAMXMSXMSMSSMXSAAASAAXSAMXSXSXMXXMXXMAMXMSMASAMXAAXAMA
            MMASAMXXMAMXMSSSMAAMXSMSSSXSXSSSMAAAAAXMAMMAAAMAMMMAMMMASXAXMSASAMXSASXXMSSMMAXXAXSMSSMMSMXAMXMAAXMASMMASMMXMAMSAAMXMAMSASXMMAAAMSMMMSSSMMSS
            XMSMXMMAMASXMAAAXSXSASXAMXAMMMAMXMMSSMMMMMASMMSSMMMSSSSSMMXXASAXXSAMMMAXMXAASMMSSSSXXXMSAXAMMAMMMSMMMXMXMAMASMMAMMMAMAXMASAXSXXXSMASXXAAAXAM
            MSMMSAMXSASAMMXMMXAXAXAMXMAMAMAMXSXXAMXAMXAMAMAXAAAMAMXAMSASMMAMXMXSAMXMXSAMXXAMMAMSMXMSASMSMMMSAMAMSXSXSMMAMMXMAXXXMXMMMMXMMAMSXMAMXASMMMMS
            SXSASXSAMASMMSAXXMMMSMMXAAMXSMMSAMAXMSSMMMMMXMMMXMXMAMMSMSAMXXASXAASAMMMXXAMSMXMMXMASAASAMAAMSAMXSAMXXSASAMAAMMXSASMMSASAAAMMAMAAMXXXAMXMASX
            SAMXMAMMXXXXAMXXXMAAXAXXMMSAMAAMMSMMXXXXAXSASMSSSSXSASXXAMAMXSAXMMMSXMAXAMXMXAMXMAXXMXMMAMXMSMXMAMMSMAMAMXMASXSAMMMAAMAMXMMSAASMAMASMMSMMSSX
            MAMSMSMASXSMSSSSMSMSSSMSMAMASXMXMAMASAMSMMAASAAAAMXSAXAMXMMAXMMMXAAXASMSSXAMMAAMXSSMMSXSAMMSXXSMMSAAMMMSMSAAMAMXSXMMSSMSSMAXMMSXMMASMXAMMAMX
            SSMSAXMXSAAAASAAXMAMMAAAMAMAMAAXSASMMAXAXXMMMMMMMMMMMMSMMXXMXAMMXMSSXMAAMSMMAMSAAXAMXAAMXXXMAAXMSXXMXAAMAMMMMAMAMXMAMAMAAMSMSXSASMASASASMASX
            XMASMMSXMMMMMMMMMMMMSMMMSXSXSMMMSXMXSXMASMXMXXMXMXMASAMXAMSMSAMXXSAXAMMMMAMSXXAMXSAMXMSMMMSMMMXXXXMSSMMMAMASXMSASAMASXMXXMXAMASAMMAXMMXMASXX
            AMMMMAXAMXMSXSXMXXMASXSAMXSXAMAAXMMXAXMAMAAAMXXXMASMMAMSSXMAMXMXXAAMMMAXSAXAMXSAMSAMXAAAAAAXAXMXXAXAAAMSMMAMAASAXXSXSXSMSMMAMXMAXMAMXSASMXAS
            XXSAMMSMMAMMAMMMSXMMXAMXXAXMMSXSAMXSSXMAXSXMASMAMAMMMMMAMMSSMMSSSMSMMSMXSMSMMMMAMMAAXSSSMSSXSSMAXSMSXMMSXMASMMMSMMMAMAMAAMXAMXMASAXXASASAMAS
            SXSAMASASASMAMXAAXSXSSMSSSMSXAMXMSAAXMAXMAMMAAMAMXSMSMMASAAAAXAAMAAMXAXXXAXXAASAMXSAMXAXMMMMXAMXSXAXXSXSAMXMAXAMXAMAMAMSMXMAMAMMSASMAMAMMMAM
            AASXMXSASAMMAXMMXXXAXXAAAMAMXSAAMXAMMSAMMSMMXSSXSAAMAMSMMMSSMMMSMMMSSXSMMMMSSXSMSAMMSAMXSXMMSAMXXMXMXMAMAMSXSMMSSXSXMXXXASXXSASXMAMMAMXMAMAS
            MMMASXMMMMMMSSMMSSMMMMMMSMMMAXSMSAXXAMASAAXXAXMASMMMMAASAAXMXXMAMXSXXAAXAAAMXAMXSAMASAXMSAMXSXMSMXAMMMAMAMXAMXMAXMAMXSAMXMAMAMXMMAMMXMXXASAX
            XASMMAAAAAAAXAMAAAXMAAXAXMSMSMMMMMSMXSMMMSXMXSMXMAMSXSASMSXSMSSSSMXAMSMSSSMMMXMASAMASASXSAMAMAMMMSMMAXAMSAMXMAMAMXASXSXSAMMXAXXMXAMMASMMXMMS
            SMSXSSMMSMMMSAMMXSMMSSMMXMAAMXAAAXAXXMASXMXSXMMAMAMXAMASAXMMAXXMXMMXMXXXAMAAASMXMAMMSAMASXMAMSASAMAAMXMSMXAXMSMSXSASXXAMAMXMMSMMSMMSASMMAAAS
            MXSAMXAAMAMAXXMSSMAAAAAXMSMSMSSMSXAAMXXSAMAMMAAASAMMMMAMAMXMSMXAAXXXMMASASXMMXMXMAMXMAMXMASASXMMASMXSAMAMSSMMAAXMMASXSMSSMMAXMAMXXAMMSASXSMS
            XAMAMMMMSXMAMSMXASMMSXMMXAAAXXAAMMMMSSMMAMXMSXAXXMXAXMXMXMASAAMSXSMAAAAMAXMSXMMASASASMMXSXMXSAXMXMAASMXXXAAASMMMXMAMMMAAXAMSXSSMXSMSASAMXAXX
            MSSSMSAMXMMSAMXSMMSMXXSXSMSMMSMMMAMXMAASAMAMAMXXAMSSMMSMMSXSMSAAAAXSMMXMXMAMAAXMXXSASXMASMMXSAMXSMMMSXMSMSSMMSSMXMASAMMMMMMMXMAMAMAMAMMAMMMM
            XAAAAAAMAXMASMAMMASXMXMASAXMAAAMSMSASMMMASXSMAMMSMAAAAXAXSXSXXMMXSAMXSMSMSMSSMSMSXMAMAMMSAMASAMXAAXXMAXAAAMAAXMXMMMSXSAAASMSASMMASAMXMMAMXAX
            MMSMMMSMMSSXMMASMMSAMMMMMMMMXSMMAASASXMSAMAMXSAAXMSSMMXXMSASMSXXMMASAMAAAAXXAMAAAAMAXXSASMMMSAMSSMMSMSAMMMSMMXSAMAASMSMSMSASXMMSMSASMMSMSSXS
            AAAASXAAAAAXXMMMXASXMAMAAAMXMXXSXXMAMAXMMSAMMXMXSXAXMMXSAMAMAMMSMSAMXSSMSMSXMSSSMXSXXXMXXXXXSXMMAAXAAXXXAXAAXASMSMMSAMAXAMXMASXAASAMMMAAMMMX
            MXXMMXSMMMSSSSSSSMXMSASMSSMSASMMSAMXMSMAAMAMAXMASMSXSAAMXMAMXMASAMAMXAMXAAXXXAAXXMMXXSAXSASXMMSSSMMMXMSSSSSSMMSAAMSMMMAMXMASXMSMMMXMASMSMSSX
            SXSSSXASXMAMAASAMXAXSASAXAAMXMAXXXMXAXSMMXMMSXMMXAMAMMXSASXSXMASMSAMXMMSASXMMMSMMAAXMASMAMXAAAAAAMXMXSAXMAMXAXMMMSAMXMMSSSXMAXMXSMXSASAAAAMM
            MAAAMAMAXMAMMMMSMMMMMXMMMMMMASXMXSSMXMAXSAMMXASXMAMXMAASAMASAMXXXMXSAAXAMXASAAXAXMXMAMMXXXSSMMSSXMAAXMAMMXMSMMMAXSMSAXAAXXMXSMSAMXASAMXMMMSM
            MMMAMAXMXSSSSMSAMXXSAMXMASXSXSASAAXAXAXASXSAXAMAMMMSSMXSAMSMMSXMXXAMMSMAAMXMASMSMMXASXMMSMMAXMXMASMSMSSMMAMXASXMMSXSMSMMSMSAMAMASMXSXSXXMASX
            XSSSSSSXMAAAAXSASMXMASXSASMMMSAMMSMSMSSXMAMXSSSXMAAXXMASXMXAAAASXMXSXMXMMMSAMXAAAXSMMAXAMXXSMSSMXMAXAAMAXASXMMAMSXAXAXAMMAMAMAMXSMXMAMAMXAMX
            AXXAAAXXAMMMMMSXMMMSMSAMXSAXAMXMAMAXAXSAMXMAAXAASMMSAMXSASMMMSSMAXAAMSAMXMMASMMXSAAASAMXSSXMASAXAMXMMMSXSMSAXSAMAMSMSSMMMMMSMMMAXXAMAMSSSMXS
            SXSMMMMSMXAAXMXMMAAAMSMASXMMXSAXXMXMSMSXMASMMMSMMAAXXMAXMMAMAMAMSMXSMSXXAXMAMAAAXMSAMXXAAXAMSXMASMSSMAMXMAMMMSMSMAAAAXXAXXAAMXMAMXXSMSAAAMAM
            XAXXXAAAMSXSMSASMMSXXXXMXMASXSASMXMAXAXAXXXMXAMMXMMXMSASASAMASMSXAMXAMASXMMASMMMMXXMMAMSMXXMMAMXXXAAMXMAMSMSASXAXSMSMMXSSMSXMAMSSMASMMMSMMMS
            XSMMMMMSXSAAASASAMMXMXMMAXSAMXXMMMASMSMXMSXMMSSMSXSAXXAAMSASXSMSMSMMAMMMSAMAXAAXXAMAMSMAASXXMASXMMSSMSMXMXAMAMSXXAXMAXAMAAMSSXSAAMAMAAAAAAAM
            AMASAMMXAMMMMMASAMXASAMSSSXXMMASASMMAXXXMXMAAAXAAASXSMXMASXMXSXXAMXMAMXAXMMXSSMMMXMAMAMMXMAAXSMMSAAAAXXMASMMSMAMXMXSAMXSAMAAMMSMSMXMMMSSSMSS
            XSAMASXMMMXAAMMSMMSXMAXAMMAMXSMSASASMSMSMAAMMSMMMXMAXAMXASMMAMXMSMMSMXMSMXMXAXXMASMMSMSSSMSSMAAMMMSSMMMMAMXAMMXSAXXXMAMXMMMASAMXMMXSAAXXXMAX
            XMASMMAAMXSSMXAXAAXMSMMMSSSMMSAMAMAMAXAAXXMXSAAAXAMXMAXMMSAXAMAAMXMASAAXASAMXMXMASAXSAMXAMAMMMMMAAXXASXAMXMSSXAXMSXSXSASXSSXMAMAAAAMSMSSMSMM
            SXXMAXSSSXAAAMSMMASXAMAXXMAAAMXMAMXMAMSSMSSXMASXMSAAXMASMSXMASMSSXSASMSMAMMMAMXMAXMMSAXSXMASAXMXMSXSAMXXMXXAAMSSXXAMAAXAAXXMXSMMMMXXXMAXASAS
            SXSSSMXAMMMMMMMAMAAMMSMSMSSMMSSSSSSMMXMAAAAAXMAMAMMSMMMMAXMSAMXAAAMAMMXMAMAMMSAMAMSASXMMSSXSMSSXXAXXMAMAMXMMSAXMXMAMASMMSMMMAXAMXXMAMAAMMMAM
            SAMAMAMAMXSXAAXAMXSXXMMMAAXAMXAAAAXXMAMMMMSSSMSMXMAAAAAMMMXMASMMMMMXMSXSSSSMASASASMASXMAAMMSXAMMMSSSSMMMAMAXMXXMAMXMMXAXXAXXMSAMAMMAXXMSXMAM
            MAMAMXXASMSMMMSSMMXMXSAMSMSSMMMMMMMSSMSXMXAAXXMMMMSSSSXSXMMSAMAXAMXMMSAMXAAMXMAMMSMAMAMXMSAMMMXAAMAMAAAMSMSMSMSMSMMAMSMMSMMMXSXMASMSMAAAXSAS
            MAMAXMMMSMMASMAMAXXAMXMMXMAXASXSXAAMAAAAMMMSMMAXAXAMXAXSMMAMASMMSSMAAMAMMSMMAMMMAXMASMMSXMASMMSMXSASMMMXMAAAAAAAAAAMXAMXAXXMAMXMXAAAMXMMMXAS
            SSSSMSAXMASXMMASMMMSMAMAXSMMXMAMMMSMMMSSMAMAMMMASMSSMXMMAMMSXMAXAAMSMSMMAXASXMAMSSSMSAAMAXSMMXAAAMXSAMXAMXMSMSMSSSMMSSSSMXSAMXXAMMSMMSSMMMXM
            AAAXASASMXMAXMXMXAMAMAXAAAXMSSMMXSAXAAXAMAMAMAXXXMAXMXXXAMXAXSXMAMMAAAAMASAMMSSSMAXAXMMXSMMAMSMMMSMSMMMXSXMAAXXXMMAXAAXMAAMMAMSXXXAAXAAASXSA
            MMMMXMASMMSMMSXMSSSSSSSMXSAMAAAAXSASMSSMSSSSSXSAMMSSMMSSMSXMMMSMSASXSMSMASAXXAMAMMMSMXMAXAMXMAAAXAXMAMSAXASMSMXAMMMMMSMXSMSMAXAMXSMXMXSMMAAS
            XMXSAMASAAXAXSAMXMAMAXXMMMAMSSMXMSXMXXXAAAXMAMMAMAMAAAAAAAXXAAAXMASAMAXMMSAMMASXMXAAAAXAMAMMSMSMMSSXMAMMSMMXMASMSAXAAAXMAMXMSSSMMXMASXMXMAMX
            AMASXMASMMSXMMAMMXMMMMSXMXMMXAMXXXAMXSMMMSMMMMMAMXSSMMSSMMMMMMMXMMMAMSXSMMMMSMMMSMMXXMMXMAMXSAAAMASXMAAXAAAMMAMASMSMXXXAMMMAMXMAMSMASAXMASXM
            XMASAMASAMXMMSSMAAXAAAMAMASXMSXSSMMMAXXMAMAXAMMMSAMXXAMXAAXXSASXAMMXMXAMXAXXMAAAAMXSXSASMMSAMMMSAASXSMSSMMSMMASAMXXAASMMXSXMXMMAMXMSSXMAAMAA
            SMMSXMXSXMAXXAXXMASXSSSMMAMAAMAMXAAMMSSMSSXSXSAAMXSMMSSSSMXASAMSAMSMMMAMSMMMSSMMSSXAAASMAMMMMSAXMXMAAXXAAAMASXSXSXMMMSAMASAXAMSXSAMXMMAMASAM
            MAMSMSMSASXSMMSSXMAMXAXASXSMMMMMMXMSXAXAMXASASMMSMSXAMAMXSSXMAMMMXXAMXAMASAXAMXAMAMMSMMSXMMXAMAXMXMMMASMMMSAMASAMASAMXMMASAMXMAXXMSAXSAMXXXX
            SAMXAAASAMXXAAAXSAMXMMMMAAAXSXMASXMMMSXSAMXMAXMASASMSMAMAXMXXMXXMASXMSXSXSXSASMXSAMXXAMXMSMMXXMMSAAAMXMASXMAMXSASAMAXMXMASXMAMMSMMMAXAXMXSMS
            SASMSMXMMMMSMMMSAMXAMAAMMSMMMAMAMAAXAXSXXXXMXMSAMAMAMXMMSSMAXXXSMASAAAXAXMASAMAXMXMXXAMASAMXSAAAXXSMSASXMASXXMSAMMSMMSAXXSASXSAAXAMSMMMMXXAA
            SAMMXSSMMAAAMSMMASXMMSSSXAAAXAMMSSMMSSMMSAMMSAMXSSMAMAAAXAMASAAAMAXMMMMMXSAMAMSMMAMMMXSMSXMASMMMSMMMSMXASMMMMAMXMMAXXSMSXSMMAMMSMMSAAXSXSMSM
            SAMAAXMASMMMMXAMAXXSAAMAMSSMSSXXAMXMXMAAMASAMXSMMAMAMXMMXMMASMXMMMSMMASAMMASAMXAMASASAAMMMMAMAAAMAAAXMSMMAASMMMMMMASXSAXMXAXAXAXAMXMSMMAXAAX
            MAXMAMXXMMASASMMSMAMMSMSAMAMAMMMSMMXAXMMSAMXSAXAXXXSSMSXSXMMXXMXAMAAMAXXASAMXMXSMMXAXSSMXAMAMSMMMSMSMXAMMXMAAXSASMAMAMAMASMSMSMSAMXXAXMAMSMS
            SXMMSSMSASAMAXXAAMAMMXAMXSAMAMMAMAMSSMMAMXSAMMSSMSMAAAXAAMXSXMASXSSSMSSMMMXXASAXASMSMMMXSXMAXXASAMMAMSAXAMXMSMMAMMAMXMAXXXXAAAXSAMXSMSSSXMAX
            SASAAMASXMASAXMSMSXSXMXMASXMASMASAMSASMASAMXSXMXAAMMMMMMMSAMAMAMXMXAMAAXSXMXXMASAMAAXXSASMMSXSAMMXMAXXAMSXSAXXMXMSXSASMSSMSMMMMMXMAAAAAMMMSM
            SAMMSMMMAAXMMSXMAMMMXMSMMMASASMAMAMMAMSAMMSAMXMMSMMXMAMMAMXSAMASXXXMMXMMSASMSMXMAMSMSXMASXAXMMSMXMSXSMMMAAMAMXMAXAAMMMAAAAMSXSASMSSMMMXMAAAA
            MAMXAAXMXMMSSMAMMMAXAMMAXXAMXMMXMAMMAMMMSAMMSAXXMASAMAMMASASMSAMMMMXMMSAMAMAAXMSAMAMAMMAMMMSAXASAMXAXXSMMMMAAASXXMAMAMMMMSMMXMASAAXXXASMMSSS
            SMMSSSMMSAMXAMMMSSSMMSSMMMSSSMSMSSMMAMAMMXMXMXSSXMAXSASXSSXSMXMMASAAXAAXMAMSMMASXSMSAXMAXAXXMMMSXSMMSMMASXMXSMAXAMXSASMMAMAAXMAMMMMMMMASXXAX
            SAMXMAAXAASXMMSAAXXMAAAAXXAAAAMAAAXSSSSSXMSSMMMXSXAXSMMXAMXXMAXSAMSSMAXSSXXAAMMMAMMMASXSSSMSXMXSAXXXAMSAMASMXXAMMSAMXMASASMMMMASAXMXAXMAXMAM
            SXMMSSMSMSMXXSMMSMSAMSSSMMMSMMMMSSMAAAAAXAAAMAXAMMSMSSMMMMMXMAMMAMAMXSMAAMSXMMAMXSXMMMAASAMSASAMXMMSMXMASAMASMMSAAAXAMAMXMMASXMMXMSSMSXMMSAM
            XMAXAXMAMAAXMSAMAAAMMAAAAXAMAXXXMAMMMMXMSMSSMSMASAMMMAXMASAAMSMSAMXSAMMXMXSXSSXSAMMXSAMXMMMMAMAXMMXAMXXMMMSSXASMXMASMSMSMXSASASMMAXAXMASASAS
            SASMMSSMSMSMASAMMSMXMMSMMMSSMMMASMMXXSMMMMAMAMSMMMMASAMXSMMSMMASXSAMXSAAXAMAMMAMMSAAMAXSMXSMAMAASMSMSSXMAXSMMMMMMXAXXAAAAMMAXAMXASXSMSMMMSAM
            ASXXXAAXXXAAMSXMAMMXMAAAXXAAAXMAMAXMXMASAMXMMMMXAXSXMSMSXXAMASAMXMAMMSMSSSMAMXMMAAMMSAMXSAASAMSSMAAXAAASMSXXAAAAXMASXMSMSMMSMSMMSXMAXAMXAMAM
            MMSSMSSMMSMSXXMAXMXAMXSSMMSSMMMSSMXMAMAMAXAMAAXMXMMXAAXMASAMMMXMXSXMAXAMAXXXSMXMXMAAXXSXMXMSMXMAMSMMSSMMXAMSMSMSSSXXAAAMAXMAMXAXMAXXSXXMSMAX
            XAAXXXXAAXMAMMASMMMMMXAMXAMAMXAAXXXSAXAXMSXSSMSAMMASXMSSMAXMXMXMAMMMSSMMMMMMXMAXAXMAXMXXMSMMMMSAMXXAAAAXMAMSAMAMAMXMMMMSSMSMSXSMMAXMMMXMASMS
            XMMSMMSSMMAXMMAAAAMASXMAMMXAMMSMMMMSMSSSXSXAAXMASMAMAAXMSMAAAMMMASXXAXXAAAAMASXSSSMMXMAAAAXAAMXXXXMMSSMMMSAMXMXMAMSAMXAXMAAXMXXAMMSAAAMSMSXS
            MAXAAAAMASXASMMSSMMAMASXAMSSMAMAMMAMXAAMASMMMSSMMMAMMXMAXXMMMXMXMXXMSSSSSXMSAMMXMAXAAMSSSMSMSSXSSMSAXAXXXMASMMASXSXXMAMMMSMAXASAMAMMXMXMXMAM
            MXSMSMXSAMXXMXMAMMMASXMMSXAMMMSAAASXMMSMAMAMAXAMXSASXMSSMXSASAMASXMAMAMXAXXMMXAMSSMXSAAXAXMMAMXAAASMSMMMXMXMASXSMSAMMAXSAMXXMASAMSXMXSMSMMAM
            SMXAMXAMAXSXMAMXMASMMAXAAMMSMXMMMMMAMAMMASMMMSAMAMXSAAAAXAMASXSASMASXMASMSAASMSAMAXAXMASMMXMASMSMMMMAXAAXMAXXMXSAMAMSMMMASASMMXXAMASXMAAASMS
            AASXSMSSSMMMSAMAMXMAXAMXSXAAXMASXXXXMAMXXSMAMSXMASASMMMSMMXMMXMXSXSXMXXAAMMXMAXSAMMMSXMSXAXMSSXMSSSSSXSSSXMXAMAMMMXMASAMAMMXAAXMASAMAMXMMMXM
            AMAMXAMAAMAAXMSXXASMMSMMXMSSSMAMMMSMSSSSMMXAMSASAMMSASXXASAXAXMMXXMASMSMSMSSSXMASXAMAMAMXSXSAMAMAXMAXAXAAAMSMMMSAXXSXSSMASMSAMSSMMMSXMSXMSAM
            SMAMMXMXMSMSXXAMSASXAAAAMMAMAMMSSMAAAAXAAMSMXSAMMSXSAMXXASMXSAMAXMASAAAAAAXMASXXXMSAMSMMAXMMASXMASMAMMMMMSMAMSASXSMSAMXSASAMMAAAMAXMAMAAMSXS
            MAAMSXMXXAAXMMAXAMXMMSMXXMAMAMMAASXMMSMMSMAMAMAMSAMXXAAMXMAAXAAXMXMASXMXMXMSXMMMMAAMMXXMXSASMMXMASMASAASXMMAMMAMASAXMAXXXMXMSSMMMSSMSSMXMMAM
            SSMASAMSSMSMMSMMMMXSMMAMSSSSSSMXXMSSSXMAXMASMMAMAMSMMSXMAMMMSMMSMAXAXXMASXMMAMMAASMXMSSXXXAMAAXMASAMSMXSAMSXMXAMXMMMAMMSSMAAMMASAMAAAXXMASAM
            XAMXMAAAAXAAMAXMAMXMAMMMAAAXAXMXSAXXAASMMSXSXSSSSSMMAMASXSMXMAAAXMMMSASASAASMMSSMXXAXAMMSXXSMSSMAMXMXXMMXMASMSASXMXSXSAAASMSXSSMAXMMMXXSAXAS
            XXMAMMMMXSXSXSXSASXMAMXMMSMMSMSAMMMMSMMSASXMAAAAMXAMXSAMXSXXXMMMSXAASXMASXMXMMMMMMSMMMSAXXMXXMAMAXMASMMSASASMAMMMSMSAMXSMXMXAMAAXMMXSSMMXSAM
            SSXSAAAXAMAXAXMSASXSASXMAMXAXAMSSMAAAAXSMSAMAMMMMXMMMXAAAMMSMMSMMMMMMAMAMMMAMAAAAXASAXMMXXAAMXMMMMSAAAASASXXMAMAMMAMXMAXXXSMXMASMSXAXAAAAMAM
            MAAMMSMSMMAMMMASAMAMAAMMASMSMXMAXMMSSMMMAXXMSSMXAASASMSMXMAMAAAMAASMSMMASXSASXMSMXAXXXAMAMSXSAAAAMMSMMMMAMASMMSSXMAMXMAMMXSAMXXXAXMAMSMMSXMM
            MMMMXMMAXMSXMMAMAMXMAMAMAXMAMMMMSAMMXAAMMMAAXAXMSMSASAAAAMSMMMSSSXSAAXMXSXSXSMMMXMSMMSXMAMAAXXXMXSAXXSAMXMMMAXAAASXMSMSMSMXXXXSMSMAMXXMAMAAS
            XAMAMMSXSMXASMMMAMXXASXMAMSAMAAASASASXMMAXXMSMMMXAMAMXMMMMMAMSAMMAMMMSMASAMMMMASAMXAMAMSXMMSMSSSMMMXMSASXSXSXMMSMMAAXAXAAMMMMMSAMXAMMXMASMMM
            SMSASAAASASAMXMSASXAMAAMAXSAXMSXXAMASMSMSMXMAXAAMMSSXAMASXSAMMXMXMMAAAMAMMMAAXASMSSXMAXXAXAAAAAAMASAAMAMMMMAXXMAMSMMMMMSMMAAAAMAMSMSAXMASAXM
            SMSASMMMMAMXMAXXXMMXMXXMXMXAMMMMMAMXSXSAAXXSSSMMSAMAMAMXSAMXSAAXAAMSMXMAXSSXSSXMMAMXSXMSMMSMMMXMSASMSMAMAAMXSXXMMAAAAXXMASXSMSMSMMMAMXXAXXMM
            MXMAMMAMMAMAMSSMXSAASXSSMSMAMAAAMXMMMAMSMMMMXMASMASMSMMAMAXXAXASMSMXMSSMMXMAXMMMMMMMASAAMAMMASAAMXSAXMMSSXSASAASXXSSSSXAXXAAMMMXASMSMSMSSSMS
            XXMAXSASMSSMXAAXAXSASAMMAAMAMMMMXAMAMXMXXMAMMXXXSAMXAASXSMSXMMMAXAASAAAXSMSSMASAMXSAMMMMMAXSAXMSMMMMMXMAMXMAMXSMSAXAMXMXMMSMMSAMAMAXAAAMAXAS
            MXXMXXASAMAMSSSMXMAXMAMMSMSMMSASMSSSSSMXSSSSMMMMMMMMSXMAAASMSASASMXMMMSMMAAMXAMASMMMXSAXXAMMASAMAMAAMXMASMMSSXXAMXMAMAMAMAMSAMXMAMAMMMMMAMSM
            SAASMMXMAMSMAAAAXXMASAMXAAAAXMASAAAAAMXAMXAAAAAAAAXXXMASMXMASASAMXXXXMAAMMMSMMSAMAAXASMSXMAMAAASAMAMSAMXSXAAAAMMMAAASASASMMMMSAMAMXSSXMMXSAM
            MXSAAASMXMAMXSMMMXXASASXMSMSMMXMXMMMAMMASMSMMSSSSSMSAMXXXXMAMXMXMSAMXSSSMSAMXAMXSSMMASAXXAXMMSXSMSAMXAXMSMXSMSMXSSSMSMSASAMXXSXSXSAMXSAMXMAS
    """.trimIndent()
    )
    check(1910, result)
}

private fun test(input: String): Int {
    val lines = input.split("\n")
    val height = lines.size
    val width = lines[0].length

    fun letter(p: Point): String {
        return if (p.x in 0..<height && p.y in 0..<width) lines[p.x][p.y].toString() else ""
    }

    fun word(p1: Point, p2: Point, p3: Point): String {
        return letter(p1) + letter(p2) + letter(p3)
    }

    fun searchTopLeft(p: Point): Boolean {
        val word = word(Point(p.x - 1, p.y - 1), p, Point(p.x + 1, p.y + 1))
        return word == "MAS" || word == "SAM"
    }

    fun searchTopRight(p: Point): Boolean {
        val word = word(Point(p.x - 1, p.y + 1), p, Point(p.x + 1, p.y - 1))
        return word == "MAS" || word == "SAM"
    }

    fun searchFrom(p: Point): Int {
        return if (letter(p) == "A" && searchTopLeft(p) && searchTopRight(p)) 1 else 0
    }

    var count = 0
    for (row in 0..<height) {
        for (col in 0..<width) {
            count += searchFrom(Point(row, col))
        }
    }
    return count
}
