package advent.advent2024

import utils.Point

private var result = 0

fun main() {
    result = test(
        """
            AAAA
            BBCD
            BBCC
            EEEC
    """.trimIndent()
    )
    check(80, result)

    result = test(
        """
            OOOOO
            OXOXO
            OOOOO
            OXOXO
            OOOOO
    """.trimIndent()
    )
    check(436, result)

    result = test(
        """
            EEEEE
            EXXXX
            EEEEE
            EXXXX
            EEEEE
    """.trimIndent()
    )
    check(236, result)

    result = test(
        """
            AAAAAA
            AAABBA
            AAABBA
            ABBAAA
            ABBAAA
            AAAAAA
    """.trimIndent()
    )
    check(368, result)

    result = test(
        """
            RRRRIICCFF
            RRRRIICCCF
            VVRRRCCFFF
            VVRCCCJFFF
            VVVVCJJCFE
            VVIVCCJJEE
            VVIIICJJEE
            MIIIIIJJEE
            MIIISIJEEE
            MMMISSJEEE
    """.trimIndent()
    )
    check(1206, result)

    result = test(
        """
            DDDDDDDDDSSSSSSSSSYWYYPPPPPPPEWEEECCRRRRROKKKKKKKKKKKKKKKKMMMMMIMMMIIIIIIIIIIIIIIIIIIIIIIIIIIVVVVVVVVVVVEEEETTTTTWWWWWWWWWQQQPBPPPPPPPAAAAAJ
            DDDDDDDDSSDDDSSSSSYYYYPPYPPPEEEEEERRRRRRKKKKKKKKKKKKKKKMMMMMMMMIMMMMMMMIMIIIIIIIIIISIISIIIVVVVVVVVVVVVVVVEEEETTWTTWWWWWWWWWQQPPPPPPPPAAAAAJJ
            DDDDDDDDDDGDDSSSSYYYYPPPYYPPEEEEEERRRRRKKKKKKKKKKKKKKKKKKEMMMMMMMMMMMIIIMMIIIMIIISSSIISIIVVVVVVVVVVVVVVVEEEEEEEWWWWWWWWWWWQQPPPPPPPPAAAAAAAA
            DDDDDDDDDDDDDDSSSYYYYYYYYYYPEEEEEEEEEERRKKKKKKKKKKKKKKKKKMMMMMMMMMMMMMMMMMMMMMMMSSSSSSSSVVVVVVVVVVVVVVVVVVVEEWWWWWWWWWWQQWQQQQPPPPPPATAAAAAA
            DDDDDDDDDDDDDDSSSYYYYYYYYYYYGYEYEEERRRRRKKKKKKKKKKKKKKKKKKMMMMMMMMMMMMMHMMMMMMMMKSVVSSSSVVVVDDVVVVVVVVVVVVEEEWWWWWWWWWWWQQQQQQPPPPPPPAAAAAAA
            DDDDDDDDDDDDDDSSSYYYYYYYYYYYYYNYEEERRRRRRKKKKKKKKKKKKKKDMMMMMMMMMMMMMMMHMMMMMMMMMSSSSSSSSVVVVLVVVVVVVVVVVEEEEEWWWWWWWWWWQQQQQQPQQAPPAAAAAAAA
            DDDDDDDDDDDDDDSSSYYYYYYYYYYYYYYYOOERRRRRRUKKKKKKKKKKKKDDDMMMMMMMMMMMMMHHMMMMMMMMSSSSSSSSSSLUULVVVVVVVVVVVEEEEEWEEBWWWWWWQQQQQQQQQAAAAAAAAAAA
            DDDDDDDDDDDDDDDDDYYYYYYYYYYYYYYYOOYCRRRRRKKDKKJKKKKKDKDDDDDMMMMMMMMMMMMMMMMMMMMMSSSSSSSSSSLLLLLVVVVVVVVVVVVEEEEEEBWWWWWQQQQQQQQQQQQAAAAAAAAA
            DDDDDDDDDDDDDDDDDYYYYYYYYYYYYYYYYYYYYDRRRRMVVVVKKKKKDDDDDDMMMMMBMMMMMMMMMMMMMMMMMSSSSSSSSSLLLLLLVVVVVZZVVVVEEEEFEWWWWWWNQQQQNQQQQAAAAAAAAAAA
            DDDDDDDDDDRDDDDDDDYYYYYYYYYYYYYYYYYYYDRRVRVVVVVKKDDKKDDDDDMMMMBBBBMAMMMMMMMMMMMIMSSXVVSSSSSLLLLVVVZVZZZYVVSSEEEFFFWWFWWNNNQQNNQQQQQAAAAAAAAA
            DDDDDDDDDDDDDDCDDDYYYYYYYYYYYYYYYYDDDDRRVRVVVVVVKDDDDDDDDDDMMMBBBMMAMMMMMMMMMMGMMSSXVSSSSSLLLLLLLVZZZZZZZZZSEEFFFFFGFFFNNNNNNQQQRRRAAAAAAAAA
            DDDDDDDDDDDCCCCCWYYWYYYYYYYYYYYYYYDDDDRRVVVVVVVVVDDVDDDDDDMMMMMMMMMMMMMMMMMMMMMMMMVVVVSVVSLLLLLLLZZZZZZZZZZZZRRFFFFFFFNNNNNNNNRRRRRRAAAAAAAA
            DDDDDDZDDDDCCCWWWWWWWYYYYYYYYYYYYYDDDDDDDVAVVVVVVVVVDDDDDDMAAAAAMMMMMMMMMMMMMMBMVVVVVSSVVSSSLLLLZZZZZZZZZZZZZRRRFFFFFNNNNNNNNNRRRRRRAAAAAAAA
            DDDDDDZDDWWWWWWEWWWWWYYYYYYYYYYYYYDDDDJJJJJVVVVVDDDDDDDDDDMAAAAAAAAAAAMMMMMMMMVVVVVVVVVGVVSSLLLSSZZZZZZZZZZZZRRRFFFFFNRRNNNNNRRRRRRRAAAAAAAA
            BBBZZDZZZWWWWWWWWWWWWKYYYYYYYYYYYYDZJJJVVVVVVVVVDDDDDDDDDDMAAAAAAAAAAAMMMMMMMMVVVVVVVVVVVVSSSSSSZZZZZZZZZZZZRRRRRFGFFFFRNNRRRRRRRRRRUAAATTAA
            PBBBZZZZWWWWWWWWWWWWYKYYYYYYYYYYYYZZJJJJJVVVVVJOODDDDDDDDDMAAAAAAAAAAAUMMMMMMVVVVVVVVVVVVVVSSSAZZZZZZZZZZZZZZRRRGGGFFFRRRRRRRRRRRRRRUAPPAAAA
            BBBBBBZZZZIIIWWWWWWWYYYYYYYYYYYYYZZZZJJJJVVVJJJOODDDDDDDDMMAAAAAAAAAAAUUMMVMMVVVVVVVVVVVVVVVSSAZZZZAAZZZZZZZZZYYFFFFFFRRRRRRRRRRRRRRRRVVVFAU
            BBBBBEIIIIIIIIWIWWWWYYYIIIIIYYYYZZZZZJIJJJJJJOOOOODDDDDDDDMMMMMMMTMMUUUUMAVVVVVVVVVVVVVVVVVVVAAADDAAAAZZZZZZZZZYYFFFFFRRRRRRRRRRRRRRRVVVVVAU
            BBEBJXIIIIIIIIWIWWWWYYIIIIIHHYYIZZZZPJIIJJJJJOOOOOODDDDDDMMMMMMMMTTHTTUUUVVVVVVVVVVEEEVVVVVVAAAAAAAAAAAZZZZZZZYYYYFFFFRORRRRRRRRRRRRRGVVVVAA
            JJBBJXXXIIIIIIIIWWYYYYIIIIIIIWIIIIZZIIIJJJJJJOOOOOOODDDDDDMMMMMMMMTTTTUTTTVVTVVVVVVVVEEVEVVAARAAAAAAAAAAAZZZZZYYYYYFFFSOWWWRRRRRRQQRGGVVVVVV
            JJJBXXOXXIIIIIIIWIIIYYIIIIIIIIIIIIIZIIIIJDDDDOOOOOOODODDDDMMMMMMMMMATTTTTTTTTTNNVVVVVEEEEEVAAAAAAAAAAAAGZZZZZZYYYYYFFFSOWTRRRRRRQQQQQVVVVVVV
            JJJBXOOXXIIIIIIIIIIIIYIIIIIIIIIIIIIZIIIIDDDDDDOOOOOOOODDMMMMUMMMMMLTTTTTTTTTTNNNVVVVEEEEEEAAAAAAAAAAAAAAZZZZZZYYYYSSSSSWWWWWWRRRQQQBQQVVVVVV
            JJJXXXXXIIIIXIIIIIIIIIIIIIIIIIIIIIIZIIIIDDDDDDOOOOOOOOOOXIMMUMMMMMMTTTTTTTTTTTTTGGVEEEEEEEEAAAAAAAAAAAAAZWEAEEEYYYYWVSWWWWWBRRRRQQQQQQQQVVVV
            JJJXXXXIXXIIXXXIIIIIIIIIIIIIIIIIIIIIIIIIIDDDOOOOOOOOOOOXXIMUUMMMMTTTTTTTTTTTTTTTTGVVEEEEEEEAAAAAAAAAAAAAZZEEEEEYEYEWWWWWWWBBRRRRQQQQQQQQVVVV
            JNJJXXXXXXXXXXXXIIIIIIIIIIIIIIIIIIIIIIIIIDDDOOOOOOOOOOOXXXUUUUUUTTTTTTTTTTTTTTTTTTGGEEEEEEEEAAAAAAAAAAAAAEEEEEEEEYEIIIIIWWWBBBQQQQQQQQQQQQVV
            JNNNXXXXXXXXXXXXXXIIIIIIIIIIIIIIIIIIIIIIDDDDDOOOOOOOOOXXXOXUUDUUUTTTTTTTTTTTTTTTGGGGEEEEEEEEAAAAAAAAAAAAAEEEEEEEEEEIIIBBBBBBBBBQQQQQQQQQQQVV
            JNNNNXXXNNNXXXXXXXIIIIIIIIIIXIIIIIIIIIIIDDDDDOOOOOOOOODXXXXDDDTTTTKKTTTTTTTTTYYGGGGGGEEEEEEEEAAPPPAAAAAACEEEEEEEEEEBBBBBBBBBBBBBQQQQQQQQQQVV
            JNNNNNNNNNNXXXXXXXIIIIIIIIIIIIIIIIIIIIIICCCOOOOOOOOOODDDXXDDDRRKKKKKTTTTTTTTTTYYGGGEEEEEEEEEEAAPPPPPAAAAEEEEEEEEEEESBBBBBBBBBBQQQQQQQQQQQQQV
            JFNNNNNNNNNXXXXXXGIIIIIPIIIIIIIIIIIIIIIIICOOOOOOOOOODDDDDDDDDRRRKKKKKTTTTTTTTTYGGGGGCEEEEEOOPAPPPPPPPAEAEEEEEEEEEIIBBBBBBBBBBBBBBQQQQQQQQQQQ
            JFFFNNFNNNNAAXXAAIIIIIIIIIQQQQQIIIIIIYIICCCCOOOOOOOOODDDDDDDDDKKKKKKKKTTTTTTTYYYGXGCCEEEEOOOPPPPPPRPPAEEZEEEETTTTTTTBBBBBBBBBBBBBQQQQQQQQQQQ
            JJFFFFFFFNAAAXAAAAAIIAAAIIIIQQQIIIIIYYICCCCCCOOOOODOODDDDDDDDDKKKKKKKKTTKKTTTYYYXXCCPPPPPOOOPPPPPPPPZZZZZWWEETTTTTTTBBBBBTTTTTBBQQQQQQQQQGGG
            FFFFFFFFFFFJAAAAAAAAAAAAAIIATQTKTTIIIYYCCCCCOOOOODDDDDDDDDDDJJJJKKKKKKKKKKKKYYYXXXCCCCPPPPPPPPPPPPPPZZZZZZEEETTTTTTTBBBBBTTTTTBBQQQQQQQQGGGG
            FFFFFFFFFFWJAAAAAAAAAAAAAIAATTTTTTTTTYYYYYCCCOOPPPDDDDDDDDDTJJJJKKKKKKKKKKKKYXYXXXXCPPPPPPPPAPPPPPPPZZZZZZEEETTTTTTTBBBBBTTTTTBBBQQQQQQQQGGG
            FFFFFFFOOWWJJAAAAAAAAAAAAAAATTTTTTTTYYYYYYYYCOOPPPDDDDDDDDDTJJJKKKKKKKKKKKKKXXXXXXXXPPPPPPPVPPPPPPPPPZZZZZZAATTTTTTTEEBBBTTTTTBBQQQQQQQQGGGG
            FFFFFFFFFFWWJAAWAAAAAAAAAAAAATTTTTTTTYYYYYYYYYYPPPPDDPDDDDTTTTTTTKKKKKKKKKKKKXXXXXXXXXXPPPPPPPPPPPPPPPPZZZCAATTTTTTTTTTEBTTTTTKKQQQQDQQQGGGG
            FFFFFFFFFWWWWWWWAAAAAAAAAAAATTTTTTTTTTTTYYYYJJPPPPPPPPDDTTTTTTTTKKKKKKKKKKKKKKXXXXXXXXXXPPPPPPPPPPPPPPPPZZCAUTTTTTTTTTTTTTTTTTBKKKQKDDQQGGGG
            FFFFFFFEFFWWWWWWAAAAAAAAAAATXTTTTTTTTTTYYYYJJJPJPPPPPDDDTTTTTTTTTTKKKKKKKKKKKXXXXXXXXXXXPPPPPPPPPPPPPPPPZZZAATTTTTTTTTTTTTTTTTBKKKKKKKKKGGGG
            FFFFFFFFWWWWWWWWWWAAAAAAAAATTTTTTTTTTATYHJJJJJJJPPPPPDDDDTSTTTTTTTKKAKKJKKKKXXXXXXXXXXXPPFHPPPPPPPPPPLPPPZAAATTTTTTTTTTTTTTTTTBBKKKKKKKKGGGG
            FFFFFFFFFWWWWWWWWWAAAAAAAAAATTTTTTTTTAAYHHHHJJJJJPPPPDDDDTDTTTTTKKKTTTKXKXXXXXXXXXXXXXPPPFHPPPPPPPPPPPPPPAAAAAATTTTTTTTTTTTTTTVKKKKKKKKKGGGG
            FFFFFFFFXWWWWWWWWWWAAAAAAKKATBBTTTTTTHHHHHHJJJJJJPPDDDDDDDDTTTTTTTTTTVKXXXXXXXXXXXXXXPPPFFFFFPPPPPPPPPPPPPAWAAABEETTTTTTTTTTTTKKKKKKKKGGGGGG
            NNNFNNNNWWWWWWWWWAAAKKAKKKKKKKTTTTTTTTTHHHHHJJJJDDDDDDDDDDDTTTTTTTTTTVVDDRDXXXXXXXXXKXPPPFFFFPPPPPPPPPPPPPPWAAABEETTTTTTTTTTTAKKKKKKKKGGGGGG
            XXNNNNNNWWWWWWWWWWAAKKKKKKKKKTTTTTTTHHHHHHHJJJJJJDDDDDDDDDDTTTTTTTTTTTTDDDDDXXXXXXXXXXPPFFFFFPPPPPPPPPPPPPPWAAAEEEAATTTTTTTTTAAKKKKKKKKGGGGG
            XXXXXNNNWWWWWWWWWGKKKKKKKKKKHHHHHTHHHHHHHHHJJJJJJDDDDDDDDDDTTTTTTTTTTDDDDDDCCCXXXXXXXXXPPFFFFPPPPPPPPPPPPWWWWWBBEEEETTTTTTTTTKKKGKKKGGKGGGGG
            XXXXXXNWWWWWWWWWWGKKKKKKKKKHHHHHHHHHHHHHHHHHJJJJJDDDDDDDDDDTTTJJJJTTJDDDDDUDCCXCXXXXXXPPPFFFFFPPPRPPPPPPWWWWWWBBEEAATTTTTTTTTJDKGKGGGGKGGGGG
            XXXXXXWWWWWWWWWWWKKKKKKKKOKHHHHHHHHHHHHHHHJJJJJJJDDDDDDDDDTTTTJJJJJJJDDDDDDDCCCCCCCXXXPPPPPFFFFPPRRPPRRPWWWWWWWBBEAATTTTTTTTTJKKKKKGGGGGGGGG
            XXXXXXXXXNWWWWWAAAKKKKOKKOOHHHHHHHHHHHHHHHHHJJJJDDDDDDDDDDTTTTJJJJJJJDDDRRRRCCCCCCCCXXPPPPPFFFFPRRRRRRRRRWWWWWWBBHHAAAAAHJJJJCCCKKBBBGBBGBGG
            XXXXXXXXXNWWWWWAAAAKAAOOOOHHHHHHHHQHHHHHHHHJJJJJJJDDDDZDTTTTTTJJJJJJDDDDRRRRRCCCCCCCXPPPPPPPFPPPRRRRRRRRRRWWWWWBBBHHHHHHHJJJCCCCKKKBBBBBBBBB
            XXXXXXXXXXWCWWAAAAAKAAAOOOHHHHHHHHHHHHHHHHHHJJJJJJDDDDZDTTTJJJJJJJJJDDRRRRRRRRCCCCCCXXPPPPPPPPPPRRRRRRRRRRRWBBBBBHHHHHHHHHJJCCCCCCCBBBBBBBBB
            XXXXXXXXXXCCWAAAAAAAAAAOOHHHHHHHHHHHHHHHHHHHJFFFFFFDIIITTTTTKKKJJJJDDDDRRRRRRRQCCCCCZPPPPPPPPXPRRRRRRRRRRRRRRBBBHHHHHHHHHHHCCCCCCCBBBBBBBBBB
            XXXXXXXXXXCCAAAAAAAAAAAOOOOHHHHHHHHHHHHHHHHJJFFFFFFIIIIIIIIIKKIJJDDDDDDRRRRRRKQXCCCZZZZXPPPPPXPRRRRRRRRRRRRRBBBBHHHHHHHHHHHCCCCCGGBBBBBBBBBB
            XXXXXXXXXXCCAAAAAAAAAAAAOOOHHHHHHHHHHHHHHHHHJFFFFFFMIIIIIIIIIIIEJDDDDRRRRRRRRQQQHCCZZZZXXXXXXXXRXRRRRRRRQQRRBBBHHHHHHHHHHHHCCCCGGGGBBBBBBBBB
            XXXXXXXXXXCAAAAAAAAAAAAOOOOOOHHHHHHHHBHQHHJJJFFFFFFFIIIIIIIIIIEEJBBRRRRRRRRRRQQQQZZZZZZXXXXXXXXXXRRRRRRRQRRRBBBBBHHHHHHHHHOHCCCGGGGGBBBBBBBB
            XXXXXXXXXXXDJJJJJJJJAAAOOOOJHHHHHHHHHHHQQQYYYYYYFFFIIIIIIIIIIIEEERRRRRRRRRRRRQQQQZZZZXXXXXXXXXXXXXRRRRRQQQQRBBBBHHHHHHHHHHHHCCCCGGGBBBBBBBBB
            XXXXXXXXXAAAJJJJJJJJAAOOOOOJHHHHHHHQHQQQQFYYYYYYFFIIIIIIIIIIIIIEEERRRRRRRRRRRQQQQQZZZXXXXXXXXXXXXXXXQRQQQSSSBBSBHHHHHCHCCCCCCGGGGGGGGNBBBBNN
            XXXQXXXXXFFAJJJJJJJJAOOOOQOOHHHHHQQQQQQQPFYYYYYYFFFIFIIIIIIIIEEEEEEEERRRRRRRRQQQQQZZZXXXXXXXXXXXXXXQQRQQQQSSSSSBSSCCCCCCCCCCCGGGGGGGGNNBBBNN
            XXXQXQQFFFFAJJJJJJJJAOOOOOOOLHHHHQQQQOQPPFYYYYYYFFFFFIIIIIIIAEEEEEEEEERRRRRRRRQQQZZZZXXXXXXXXXXXXXXXQQQSSSSSSSSSSSCCCCCCCCCCCCCGGGGGGGNNNNNN
            BXQQQQQQQFFFJJJJJJJJOOOOOOOOOQQHQQQQQQPPPPYYYYYYFFRFIIIIIIAAAEEEAEEEEERRRRRRRRQQQZZZZXXXXXXXXXXXXXXXXQSSSSSSSSSSSSCCCCCCCCCCCCGGGGGGGGGNNNNN
            QQQQQQQQFFFFJJJJJJJJOOOOOOOOOOQQQQYYYQQPPPYYYYYYYYYYIIIIIIAAAAAEAEEEEEERRRRRRRZZZZZZZXXXKXPXXXXXXXXXXSSSSSSSSSSSSCCCCCCCCCCCYCGGGGGGGGNNNNNN
            QQQQQQQQFFFFJJJJJJJJAOOOOOOOOQQQQQQYPPPPPPYYYYYYYYYYIIIIIAAAAAAAAAEEHEERRRRZZZZZZZZZZZXXKPPPXXXXXXBXXSSSSSSSSSSSSCCCCCCCCCCCCCCGGGGGGGNNNNNN
            MQQQQQQFFFFFJJJJJJJJJJJJJJJJJJJQYYYYYPPPPPPPPPYYYYYYIIIIIAAAAAAAAAEHHEERRRRZZZZZZZZZZZLLPPPPPPDDXDDDDHSSSSSSSSSSSCCCCCCCCCCCCCCGGGGGGGGGNNNN
            MQQQQQQFFFFFJJJJJJJJJJJJJJJJJJJYYYYYYPPPPPPPPIYYYYYYIIIIIAAAAAAAAAHHHHERKRRZZZZZZZZZZZPPPPPPPMDDDDDDDHSSSSSSSSSSSGCCCCCCCCCCCCGGGGGGGGGNNNNN
            QQQQQQQQFFJJJJJJJJJJJJJJJJJJJJJYYYYPPPPPPPPPPYYYYYYYCIIIIIAAAAAAAAAHHHEERRZZZZZZZZZZZZPPPPPPPPDDDDDDDHHSSSSSSSSSSGGGCCCCCCCCCCGCGGGGGGNNNNNN
            QQQQQQQQFFJJJJJJJJJJJJJJJJJJJJJYYYYYPPPPPPPLLYYYYYYYCIIIIAADAAAAAAAAHHHERRZZZZZZZZZZZZZPPPPPPDDDDDDDDDHHSSSSSSSGSGGGCCCCCCCCCCCCCGGGGGGNNNNN
            QQQQQQQFFYJJJJJJJJJJJJJJJJJJJJJYDYYYYYPPPPLLPYYYYYYYCIIJJJAAAAAAAAAAHHHEHRZZZZZZZZZZZZZOPPVVPDDDDDBDHHHHSSSSSSGGGGGGGCCCCCCCCCCWCCGGGGGNNNNN
            QSSSSSFFFFJJJJJJJJJJIIIIIEEEEEYYYYYYYYYYPPLLLYYYYYYYCCCCCJJJAAAAAAAHHHHHHRZZZZZZZZZZZZZOOOVVVDDDDDDDHHHHHHSGGSGGGGGGGGGCCCCWCWWWWCWNNNNNNNNN
            SSSSSFFFFFJJJJJJJJJJJIJIIEEEEEEYYYYYYYYYPPKLLYYYYYYYCCKCKAAJAAAAAAHHHHHHHRZZZZZZZZZZZZZOOVVVVVDDDDDHHHMMMMMMGGGGGGGGGGGGWCWWWWWWWWWWWWNNNNNN
            SSSSSSSYYFJJJJJJJJJJJJJEEEEEEEEYYYYYYYCPPPLLLYYYYYYYCCKKKAAAAAAAAAHHHHHRRRZZZZZZZZZZZZZOOHHHHVHDDDHHHMMMMMMMMGGGGGGGGGWGWWWWWWWWWWWWNNNNNNNN
            SSSSSSSLYFJJJJJJJJJJFFJJEEEEEEWYYYYYYYCPPPPMMYYYYYYYCCCKKAAAAAAAAHHHHHHRRRZZZZZZZZZZZZZHHHHHHVHHHDDDHHMMMMMMMGGGGGGGFFWWWWWWWWWWWWWNNNNNNNQQ
            SSSSSSSLYYJJJJJJJJJJJJJJEEEEEEWWYYYYYYCPPPPPPYYYYYYYCCCKKAAAAAAAAAHHHHHHHHZZZZZZZZZZZZZHHZHHHHHHHHDHHMMMMMMMGGGGGGGGWWSWWWWWWWWWWWWNNNNNNNMQ
            SSSSSSSSYYJJJJJJJJJJJJJJJEEEEEEWWWWWYLNBNNPPCYYYYYYYCCCCKAAAAAAAAAHHHLLQLRZZZZZZZZZZZZZHHZHHHHHHHHHHHHMMMGGMGGGGGGGGWWSWWWWWWWWWWWWNNNNNNSQQ
            SSSSSSSJJYJJJJJJJJJJJJJJJJJEEEEWWWWNNNNNNNNPPCCCCCCCCCCCCAAGGXAAAAHHHPLQLLZZZZZZZZZZZZZHHHHHHHHHHHHHHHMMMMGGGGGGGGGMWWWWWWWWWWWWWWNNNNNNNNQQ
            SSSSSSSSJYYYYYYYYYJJJJJJJJJJJJEJJJWNNNNNNNNNYCCCCCCCCCGGGAGGGGAAAAHHLLLLLLLRBBPPPPPPHHHHHHHHHHNHHHHHMMMMMMVGVGGPGGGGWDWWWWWWWWWWWWNVNNNNNNQQ
            SSSSSSSSJJYYYYYYYYYYJJJJJJJJJJJJJJWNNNNNNNCCCCCCCCCCCCCGGGGGGGAMMGTLLLLLLBBBBBYPPPPPPPHHHHHHNNNNHHUUUVVVVVVVVVVGGVGGWDDWWWWWWWWWWWVVVNNQQQQQ
            SSSSSSYJJYYYYYYYYJJJJJJJJJJJJJJJJJNNNNPPPPCCCCCCCCCCCCCCGGGGGGAMGGTTLLLLLLLBBXYYPPPPPPPPHHHHVNNNHHUUUVVVVVVVVVVVGVVVVDDWWWWWWWWWWWVVVNNNQQQQ
            SSSSSSYYJYYYYYYYYYJJJJJJJJJJJJOOOOOONNPPPPPPPXXXLCCCCCCGGGGGGGGGGGGGBLLLLLBBYYYYYPPPPHHHHHHUVNNNUUUUUUUUVVVVVVVVGVVVDDDWWWWWWWWWWVVVNNQQQQQQ
            SSSSSSSYYYYYYYYYYYJJJJJJJJJJJJOOOOFFFFPPPPPPPXXXXXCCCXGGGGGGGGGGGGGBBBBLBBBBYYYYYYPPPHHHHHUUVNUUUUUUUUUVVVVVVVVVVVVVDIDDDDWWWWWWVVVVNNQQQQQQ
            SSSSSSSYYYYYYYYYYYJJJJJJJJJJJJJWWOFFFFPPPPPPPPPSSSSSCXGGGGGGGGGGGGGBBBBBBBYBBYYYYYPPPYHHHHBUUNUUUUUUUUUJVVVVVVVVVVVDDDDDDWWWVWWWVVVVQQQQQQQQ
            SSSSSSYYYYYYYYYYYYYJJJJJJJJJJEEWWOFFFFPPPPPPPPPSSSSSSGGGGGGGGGGGGGGBBBBBBBYYYYYYYYYYYYYHHEUUUUUUUQQQQQQVVVVVVVVVVVVDDDDDDWVVVVVWVVVVQQQQQQQQ
            SSSSTTYYYYYYYYYQQQQJJJJJJJEEJEEEWOFFFFPPPPPPPPPSSSSSSGGSGGGGGGGGGYGGBBBYYYYYYYYYYYYYYEEEEQQQQQQQQQQQQQQFVMVVVVVVVVVDDDDVVVVVVVVVVVVQQQQQQQQQ
            USSSTTYYYCCYYYYPQQQQJJJEEEEEEEEEOOFFFFPPPPPPPPPXSSSSSSSSSSGGGGGGGGGBBBYYYYYYYYYYYYYOYEEEEQQQQQQQQQQQQQQFFFVVVVVVVDDDDDVVVVVVVVVVVVVVQQQQQQQQ
            USSSTTTTTTTYYYYQQQQQQEEEEEEEEEEFFFFFFFPPPPPPPPPXSSSSSSSSGGGGGGGGBBBBBBBYYYYYYYYYYYOOOEEEEQQQQQQQQQQQQQQFFFVVVVVVVFDDDDVVVVVVVVVVVVVVQQQQQQQQ
            SSVTTTTTTTTTYQQQQQQQQEEEEEEEEEEFFFFFFFPPPPPPPPPXSSSSSSSSGGGGGGGGGBBBBBBYYYYYYYYYYYOOOAAAAQQQQQQQQQQQQQQEFFFVVVVVVFFFRVPVVVVVVVVVVVVVVVVQQQQQ
            STTTTTTTTTTTCCCCQQQQQEEEEEEEEEEFFFFFFFPPPPPPPPPKSKSSSSSSSGGGGGGGGBBBBBBBYYYYYYYOYOOOOOAAAQQQQQQQQQQQQQQTTTFFFFVVFFVVVVVVVVVVSVVVVVVVVVVVQQVV
            TTTTTTTTTTTCCCQQQQQQQEEEEEEEEEEFFFFFFFFFFPPPPPPKKKSSSSSSSGGGGGGGGJBBBBBBBOOOOYYOOOOOOOQQQQQQQQQQQQQQQQQTTTTTFFFVVFVVVVVVVVVSSSSSSVVVVVDQQQVV
            JTTTTTTTTTTCTCCQQQQQEEEEEEEEEEEFFFFFFFFFFPPPPPPKKKKSSSSHSGHGGGQBBBBBBBBBBOOOOOOOOOOOOOQQQQQQQQQQQQQQQQTTTKTTFFFFFFFFVVVVVVVSSSSSSVVVVVDVQVVV
            JTTTTTTTTTTTTCQQQQQQEEEEEEEEEEEFFFFFFFFFFFFFFKKKKKKKSSSHHHHGGGHBBBBBBBBBBOOOOSSSSOOOOOQQQQQQQQQQQQQQQQCTTTTFFFFFFFFFFVOOVSSSSSSSSSVVVVDVVVVV
            JTTTTTTTTTTTTCQQQQQQQEEEEEOOOOOFFFFFFFFFFFFFFCKKKKKKKSHHHHHRRGHHBBBBBBBBALOOSSSSSOOOAAQQQQQQQQQQQQQQQQTTTTFFFFFFFFFFFFOVSSSSSSSSSDDDDDDVVVVV
            JJJTTTTTTTTTTCQOQQQQQEEEEOOOOOOFFFFFFFFFFFFFFKKKKKKKKKNHHHHHRHHHHHBBBAABALOSSSSSSOHOAAQQQQQQQQQQQQQQQQCTTTFFFTTTFFFFFFOOTTSSSSSSSDDDDDDDVVVV
            JJTTTTTTTTKTTCQOOQQQQEEOOIOOOOOFFFFFFFFFFFFFFKKKKKKKKKHHHHHHHHHHHHBBBAAAALOOSSSSHOHQQQQQQQQQQAAAAAQQQQCTTTTFTTTTTTFFFOOOTTSSSSSSSDDDDDDDDVDV
            JJJTITTTTKKKTXOOOQQQEEEOOOOOOOOFFFFFFFFFFFFFFKKKKKWWWWHHHHHHHHHHHHHBBAAALLLOSSSSSLLQQQQQQQQQQAAAAAACCCCTVTTTTTTTTTQFOOOOTTTSSSBBBBDDDDDDVVDV
            JJJTIIRTTKKKXXXXXQQQPYOOOOOOOOOQQQZZZTFFFFQFFKQQHHHHHWHHHHHHHHHHHWVVBAALLLLOOOLLLLLQQQQQQQQQQAAAAACCCTCTTTTTTTTTTMCOOOOOOOOOBBBBBBDDDDDDVDDD
            IIIIIIITTIKKIZXXXXDYYYOOOOOOOOOOQQZZQQQFFFQQQQQQHHHHHHHHHHHHHHHHWWWVWWALLLLLOOLLLLLQQQQQQQQQQAAAACCCCTTTTTTTTTTTGCCCOOOOOOOOOODDDDDDDDDDDDDD
            IIIIIIITIIIIIZXXXXYYYYOOOOOOOOOQQQQQQQQFQQQQQHHHHHHHHHHHHHHHHHHWWWWWWWAWYLLLLLLLLLLQQQQQQAYAAAAAACCCTTTTTTTTTTTTGGCOOOOOOOOOOOODDDDDDDDDDDDD
            IIIIIIIIIIIIIIXXXXYYYYYOOOOOOOOQQQQQQQQQQQQQQRHHHHHHHHHHHHHHHHHWWWWWJWWWYLLLLLLLLLTQQQQQQYYYAYAAACTTTTTTTTTTTTTTTTCCOOOOOOOOOOODDDDDDDDDDDDD
            IIIIIIIIIIIIIXXXXYYYYYYYYOOOOOOQQQQQQQQQQQQRRRHHHJHHHHNHHNHHHHWWWWWWWWWWYLLLLLLLLLTQQQQQQYYYYYYAYCTTTTTTTTTTTTTCTCCCCCFOOOOOOOOODDDDDDDDDDDD
            IIIIIIIIIIIIIIXXXYYYYYYYYYYYOQOQQQQQQQQQQQQRRQHHJJHHHNNNNNNNHHWWWWWWWWYWYYLLVLLLLLTTTTTTYYYYYYYYYYYTTTTPATTTTTTCCCCCCCCCOOOOOOOODDDDDDDDDDDD
            IIIIIIIIIIIIXXXXXXYYYYYWWWWQQQQQQQQQQQQQQQQRQQJJJJHHHHNNNNNNNNWWWWWWWWWYYVVLVLLLLLTTTTTTTYYOOOYYYYYTTTAAATZZTTCCCCCCCCOOOOOOOOOODDDDDDDDDDDD
            IIIIIIIIIIIIZXZXZXYYYYYWWWWWQQQQQQQQQQQQQQQQQQQEEJJJHHNNNNNANNWWWWWWWVWWVVVVVTTLLLTTTTTTYYYOYYYYYYYYTTTAAATTTCCCCCCCCOOOOOOOOOOOOXXDDDDDDDDD
            IIIIIIIIIIIIZXZZZYYYYYYWWWWWSSQQQQQQQQQQQQQQQEEEEEEJJJJNNNNAAWWWWWWWWVVVVVVVVTTLTTTTTTTTTTOOYOYOYYYYTTAAAAAAACCCCCCCCCOOKOOOOOFOBUUDDDDDDCDD
            VVIIIIIIIIIIZZZZZYYYYYWWWWWWWWQQQQQQQQQQEQEEQEEEEEEEJJJJNNNNAWWWWWWWWWVVVVVVVTTTTTTTTTTTTTOOOOOOOOYYYAJAAAAACCCCCCCCCCOOKOOOKKOOUUUUUUDDCCCC
            VVIILIIIIIIIZZZZZZYZZWWWWWWWWWWQQQKQQQQQEEEEEEEEEEEEJJWWWWWWAWWWWWWWWVVVVVVHVTVTTTTTTTTTTOOOOOOOOOOYYAAAAAAAACCCCCCCCCOOKKKKKKUUUUUUUCCDCCCC
            VVVIIIIIIIIZZZZZZZYZZWWWWWWWWWWQQQWQEEEQQEEEEEEEEEEWWJWWWWWAAAWWWWWWWWVVVVVVVVVTTTTTTTTTTOOOOOOOOOOAAAAAAAAACCCCCCKCKKKKKKEKUKUUUUUCCCCCCJCC
            VVVVVIIIIIZZZZZZZZZZZZZWWWWWWWWWQWWEEEEQEEEEEEEEEEERWWLWWWWAAWWWWWWWWWVVVVVVVVVTTTTTTTTTOOOOOOOOOOAAAAAAAAAACCCCCKKKKKKKEEEKUUUUUUUJJJJJCJJC
            VVVVVVVIINZYZZZZZZZZZZZWWWWWWWWWWWWEEEEEEEEEEEEEEWWWWWWWWWWAAAAWWWWWWWWVVVVVVVVVTTTTTTOOOOOOOOOOOOAAAAAAAAAAACACCKKKKKKKKEEEEUUUKKUJJJJOJJJJ
            VVVVVVVIINZYZZEVPVVVZZZZWWWWWWWWWWWWWEEEEEEEEEEEEEWWWWWWWWWAKAAAAKEKWRRVVVVVVVVVITTTTOOOEEOOOOEECAAAAAAAAAAAAAACKKKKKKKEEEEEEEKKKKKJJJJJJJJJ
            VVVVVVVVMMMMZEEVVVVVZZZZZZWWWWWWWGWEEEEEEEEEEEMMMEEWWWWWWKKKKKAKKKKKRRRZVVVVVVVVTTTTTOOOEQEOOEEECAAAAAAAAAAAAAAAAAAKKKKEEEEEEEKKKKKJJJJJJJJR
            VVVVVVVVMMMMJVEEVVVVVVVVVWWWWWWGGGEEEEEEEEEEEEMMMEEEWWKWWXXXKKKKKKKKRZZZZVVVVDDDDDDTEEOEEQEEEEEMEQQQAAOAAAAAAAAAAAAKEEEEEEEEEEKKKRRRRJJJJJRR
            VVVVVVVMMMMMVVVVVVVVVVVVTWWWWGGGGGGGEEEEEEEEEEMMMMEETKKKKXXKKKKKKZZZRZZZZVVVVDDDDDDTEECEEEEEEEEMEEAAAAOAAAAAAAAAAAAKEEEEEEEEEEEKKRRRRRRRJBRR
            VVVVVVMMMMMMMMVVVVVVVVVVVVGGGGGGGGGGGEEEEEEEDDMMMRRETTTKKKKKKKKKKZZZZZZZYVVVVDDDDDDDEEEEEEEEEEEEEEOAAZOOAAAAAAAAADDLWWWWEEELEILKRRRRRRRRRRRR
            VVVVMMMMMMMMMMMVVVVVVVVVVGGGGGGGGGGGGGEEEDEDYDMMMMEETTTKKKKKKKKKKKKZZZZZZVVVDDDDDDDDEEEEEEEEEEEEEEOOOOOOOAAALALLLDDLEEEEEELLIILRRRRRRRRRRRRR
            VVVVVMMMMMMMMMVVVVVVVVVVVVGGGGGGGGGGGGEEDDDDDDMMMMTTTTKKKKKKKKKKKKKZZZZZZZDDDDDDDDDEEEEEEEEEEEEEEEOOOOOOOOOOLLLLLDLLLLLEELLLLLLLRRRRRRRRRRRR
            VVVVVMMMMMMMMMVVVVVVVVVVVSGGGGGGGGGGGEEDDDDDDTDMMMTTTTKKKKKKKKKKZZZZZZZZZZZZDDDDDDDEEEEEEEEEEEEEEOOOOOOOOXLLLLLLLLLLLLLLLLLLLLLLRRRRRRRRRRRW
            VVVMMMMMMMMMMMVVVVVVVVVVVSGGGGGGGGGGSDDDDDDDDDDTTMTTTKKKKKKKKKKKZZZZZZZZZZZDDDDDDEEEEEEEEEEEEEEEEOOOOOOOLLLLLLLLLLSLLLLLLLLLLLLLLRRRRRRRRRRR
            VVVVMOOMOMMMMBBVVVVVVVVVVSSSGGSSSSGSSSDDDDDDDDDTTTTTTTKFFKKKKKKKZZZZZZZZZZZZDDDDDDDEEEEEEEEEEEEEOOOOOOOOLLLLLLLLLLSSSLLLLLLLLLLLLRRRRRRRRRRR
            VVOOOOOOOOMMPBPPVVVVVVVSSSSSGGGSSSSSSDDDDDDDDTTTTTTTTTTLFFKKKKKKKKKZZZZZZZIIDDDDDDDEEEEWEEEEEEEEKKKKOOOOLLLLLLLLLLSSSSLLLLLLLLLLLLRRRRRRRRRW
            VVOQOOOOOOMMPPPPPVVVVVVVSSSSSSSSBSSSSSSDDDDDDDDDTLLLTTTLFFKKKKKKKKKDDZZZZZZDDDDDDDDDDEEEEEEEKKEKKKKLLLLLLLLLLLLNLLSSSLLLLLLLLLLLLRRRRRRRRRRW
            VVOOOOOOOOMPPPPPPVVVHVVVSPSSSBBBBBSSSDDDDDDDDZDDTLLLLLLLLFFKKKKBBKKDDDDDDDDDDDDDDDDDDEEKEEKKKKKKKKKLLLLLLLLLLLLLLLSSSLLLLLLLLLLLRRRRRRRRRRRW
            VVVOOOOOOOMPPPPPPPPVHPVSSPSSSSBBBBBBBBCDDDDZZZZLLLLLLLLLLFFVVVVVDDDDDDDDDDDDDDDDDDDDKKKKKKKKKKKKKKFLLLLLLLLLLLLLLLLLSSSLLLLLYLDRRRRRRRRRWWWW
            VVVVOOOOOOSPPPPPPPPVVPEPPPSSSBBBBBBBBBLDLMLLZZLLLLLLLLLVVVVVVVVVVDDDDDDDDDDDDDGDDDDDDKKKKKKKKKKKKFFFIIOLLLLLLLLLLLLLLSSSLLYYYYRRRZZRRRRRRWWW
            VVVOOVOOOOOPPPPPPPPPPPPPPPSSBBBBBBBBBBLLLLLLZLLLLLLLLLLVVVVVVVVVVDDDDDDDDDDGDDDDDDDFDKKKKPPKKKKKKFFFFIOLLLLLLLLLLLLLLSSSLKYYRRRRFFZKZZDDZZZZ
            VVVOOVVVVOPPPPPOPPPPPPPPZPSSBBBBBBBBBBBLLLLLZZLLLLLLLLLVVVVVVVVVVVDDDDDDDDDDDDDDHFFFFKPPPPPPPPPPPFFFFLLLLLLLLLLLLLLLLSSSKKYYYRRFFFZKZZDZZZZZ
            VVVVVVOOOOOOOOOOOPPPPPPPZZSBBBBBBBBBBBLLLLLLLLLLLLLLLLVVVVVVVVVVVDDDDDDDDDDDDDLUUFFFFFPPPIIIIIPPPFFFFFFLLLLLLLLLLLLLSSSKKKKKYKRFFZZZZZZZZZZZ
            VVVVOVVOOOOOOOOWOPPPPPPPPPSSIIIIIIIIBBLLLLLLLLLLLLLLLVVVVVVVVVVVVDDDDDDDDUUDDUUUUUUUFFPPPIIIIIPPPFFFFFFLLLLLLRRRRLSSSKKKKKPKKKFFZZZZZZZZZZZZ
            VVOOOOOOOOOOOOOOOOSPPPPPPSSSIIIIIIIIBLLLLLLLLLLLLLLLLVVVVVVVVVSSSDDDDDDDUUUDDUUUUUUIIIIIIIIIIIPPPFFFFFFRRLLLLRRRRSSSSKYKKKKKKKFZZZZZZZZZZZZZ
            OOOOOOOOOOOOOOOOSSSPPPPSSSSSIIIIIIIIBLLLLLLLLLLLLLLLLLFVVVVVVVSSDDDDRRRDUUUUUUUUUIIIIIIIIIIIIIPHPFFFFFRRRLLRRRRSSSSSSSKKKKKKKFFZZZZZZZZZZZZZ
            LOOOOOOOOOOOOOOSSSSSPSSSSSSSIIIIIIIIBLLLLLLLLLLLLLLLLLVVVVVVVVSSSSDRRRRUUUUUUUUUUIIIIIIIIIIIIIPPPPFFFFFRRRRRRRRRSSSKKKKKKKKKKZZZZZZZZZZZZZZZ
            OOOOOOOOOOOOOOOSSSSSPSSSSSSSIIIIIIIIBBNNNNLLLLLLLLLLLLVVVVVVVVSRRSDRRRRRUWUUUUUUUIIIIIIIIIIIIIPPPPFFFFFFRRRRRRRRSSSSKKKKKKIJJYZZZZZZZZZZZZZZ
            OOOOOOOOOOOOOOOOSSSSSSSSSSSSIIIIIIIINNNNNNLLLLLULHLLLLVVVVVVVVRRRRRRRRRUUWWUUUUUUIIIIIIIIIIIIIPPPPPFFFRRRRRRRRRRSSSSKKKKJJJJJYZZZEPZZZZZZZZZ
            OOOOOOOOOOOOOOOOGGSSSSSSSSSSIIIIIIIINNNNNNLLLLLLHHHHHHVVVVVVVDFRRRRRRRRRRWWUUUUUUIIIIIIIIIIIIISSSXSFFFRRRRRRRRRRRRJKKKKKKJJJJJPPPPPZZPZZZZZZ
            OOOOOOOOOOOOOOOOGGSSSSSSSSSSSSBBBBBBNNNNBNNLLLLLHHHHHVVVVLDZVDFRGRRRRWWWWWWUUWUUUUUIIIIIIIIIIIPPSSSFFFRRRRRRRRRRRJJKKKKKJJJJJJPPPPPPPPPPPZZZ
            OOOOOOOOOOOOONGGGGGSSSSSSSSSSSBQBBBBBNNNBBBLLLLLBHHHVVVVVDDDDDDDRRRWWWWWWNWWWWWWUUVUUVPPPPPPPPPSSSSSFFRRRRRRRRRNRJKKJJJKJJJJJHPPPPPPPPPPPPPZ
            OOOOOOOOOOOOOODGGGGGSSSSSSMMMMMMBBBOBBNNBBBBBLLBBBBBVVVVVDDDDDDDRRRKWWWWWWWWWVVVVUVVVVUPPPPPPPPSSSSSWRRRRRRRRRRRRJJJJJJJJJJJJPPPPPPPPPPPPPPP
            OOOOOOOOGGLLGGGGGGGGGGGSMMMMMMMOOOOOBBNNBBBBBBBBRBBDVVVVVDDDDDWWWWWWWWWWWWWWWWWWVUVVVVUUPPPSPPSSSSSSSSSRRRRRRRRJJJJJJJJJJJJUUIUPPPPPPPPPPPPP
            OOOOOGGGGGGGGGGGGGGGGMSSMMMMMMMMOOBBBBBBBBBBBBBBBBBDDDVDDDDDDDGWWWWWWWWWWWWWWWWVVVVVVVUUPPPSSSSSSSSSSSSRRRAAARRJJJJJJJJJJJUUUUUUPPPPPPPPPPPF
            OOOOGGGGGGGGGGGGGGGGGMMSMMMMMMMMOOMMBBBBBBBBBBBBBBBDDDDDDDDDDGGGGGWWWWWWWWWWWVWVVVVVVVUUUPSSSSSSSSSSSSSRAAAAAJJJJJJJJJJJJJUUUUUPPPPPPPPPPPPP
            OOOOGGGGGGGGGGGGGGGGGMMMMMMMMMMMMMMMBBBBBBBBBBBBBBBBDDDUUUDDDGGGGGWWWWWWWWWWWVVVVVVVVVUUUUCSSSSSSSSSSSSSSAAAAJJJJJJJJJJJJJUUUUUPPPPPPPPPPPPP
            OOOOGGGGGGGGGGGGGGGGGMMMMMMMMMMMMMMBBBBBBBBBBBBBBBBBBUDDUUUDDGGGGWWWWWWWWWWWWWVVVVVVVVUUUUSNSSSSSSSSSSSSSSSAXJJJJJJJJJJJJUUUUUUPPPPPPPPPPPPP
            OOOOGOGGGGGGGGGGGGGGGMMMMMMMMMMMMMBBBBBBBBBBBBBBBBBPUUUUUUNUDGGGGGWWWWWWWWWWWVVVVVVVVVUUUUSNSSSSSSSSSSSSDSSXXJJJJJJJJJJJJUJJUUPPPPPPPPPPPPPP
            OOOOGOGGGGGGGGGGGGGGGMMMMMMMMMMMMBBBBBBBBBBBBBBBBBBPPPUUUUUUUGGGGGWGWWWWWWWWWVVVVVVVVVVVUUSSSSSSSSSSSSXSSXXXXJJJJJJJJJJJJJJJUUUPPPPPPPPPPPPP
            OOOOOOOOGGGGGGGGGGGGGMOMMMMWMMMCMBBBBBBBBBBBBBBBBBPPPUULUUUGGGGGGGGGGWIIIWGWVVVVVVVVVVVVUUYYSSSHSSSSTSXXXXXXXXXJJJJJJJJJJJUUUUPPPPPPPPPPPPPP
    """.trimIndent()
    )
    check(936718, result)
}

private fun test(input: String): Int {
    val map = input.split("\n")
    val height = map.size
    val width = map[0].length

    fun isInsideMap(point: Point): Boolean {
        return point.x in 0..<height && point.y in 0..<width
    }

    fun Point.generateNext(plot: Set<Point>): Set<Point> {
        val results = mutableSetOf<Point>()
        val set = setOf(Point(0, 1), Point(1, 0), Point(0, -1), Point(-1, 0))
        for (delta in set) {
            val next = Point(x + delta.x, y + delta.y)
            if (isInsideMap(next) && map[next.x][next.y] == map[x][y] && next !in plot) {
                results += next
            }
        }
        return results
    }

    fun bfs(startPoint: Point): Set<Point> {
        val plot = mutableSetOf<Point>()
        var opened = mutableSetOf<Point>()
        opened += startPoint
        plot += startPoint
        while (opened.isNotEmpty()) {
            val achievable = mutableSetOf<Point>()
            for (current in opened) {
                val next = current.generateNext(plot)
                for (nextPoint in next) {
                    achievable += nextPoint
                }
            }
            opened = achievable
            plot += achievable
        }
        return plot
    }

    val plots = mutableSetOf<Set<Point>>()
    for (x in 0..<width) {
        for (y in 0..<height) {
            val foundNew = plots.none { it.contains(Point(x, y)) }
            if (foundNew) {
                val plot = bfs(Point(x, y))
                plots += plot
            }
        }
    }

    fun adjacent(point: Point, plot: Set<Point>): Set<Point> {
        val results = mutableSetOf<Point>()
        val set = setOf(Point(0, 1), Point(1, 0), Point(0, -1), Point(-1, 0))
        for (delta in set) {
            val next = Point(point.x + delta.x, point.y + delta.y)
            if (next in plot) {
                results += next
            }
        }
        return results
    }

    fun perimeterOf(plot: Set<Point>): Int {
        var p = 0
        for (point in plot) {
            val adjacentCount = adjacent(point, plot).size
            if (adjacentCount == 0) {
                println("$point p+4")
                p += 4
            } else if (adjacentCount == 1) {
                println("$point p+2")
                p += 2
            } else {
                val masks = listOf(
                    setOf(Point(0, 0), Point(-1, 0), Point(0, 1)),
                    setOf(Point(0, 0), Point(1, 0), Point(0, -1)),
                    setOf(Point(0, 0), Point(-1, 0), Point(0, -1)),
                    setOf(Point(0, 0), Point(1, 0), Point(0, 1))
                )
                val inMasks = listOf(
                    setOf(Point(-1, 1)), setOf(Point(1, -1)), setOf(Point(-1, -1)), setOf(Point(1, 1))
                )
                val outMasks = listOf(
                    setOf(Point(0, -1), Point(1, 0)),
                    setOf(Point(0, 1), Point(-1, 0)),
                    setOf(Point(0, 1), Point(1, 0)),
                    setOf(Point(-1, 0), Point(0, -1))
                )

                fun applyMask(point: Point, mask: Set<Point>): Set<Point> {
                    val results = mutableSetOf<Point>()
                    for (delta in mask) {
                        results += Point(point.x + delta.x, point.y + delta.y)
                    }
                    return results
                }
                for (i in masks.indices) {
                    if (applyMask(point, masks[i]).all { it in plot }) {
                        val inside = applyMask(point, inMasks[i]).none { it in plot }
                        val outside = applyMask(point, outMasks[i]).none { it in plot }
                        if (inside && outside) {
                            p += 2
                            println("$point p+2 in out")
                        } else if (inside) {
                            ++p
                            println("$point p+1 in")
                        } else if (outside) {
                            ++p
                            println("$point p+1 out")
                        }
                    }
                }
            }
        }
        println("$plot -> p=$p")
        return p
    }

    var fiyat = 0
    for (plot in plots) {
        fiyat += plot.size * perimeterOf(plot)
    }

    return fiyat
}
