package advent2019;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AoC2019Day6Part1 {

    public static void main(String[] args) {
        int result;

        result = test("COM)B\n" +
                "B)C\n" +
                "C)D\n" +
                "D)E\n" +
                "E)F\n" +
                "B)G\n" +
                "G)H\n" +
                "D)I\n" +
                "E)J\n" +
                "J)K\n" +
                "K)L");
        assert result == 42 : "unexpected result is " + result;
        System.out.println(result);

        result = test("YMK)12Q\n" +
                "N3N)11S\n" +
                "P73)8Q3\n" +
                "PC8)14H\n" +
                "CDH)SR2\n" +
                "Z3F)KJF\n" +
                "3QM)NMC\n" +
                "GYV)H9S\n" +
                "7WN)TSD\n" +
                "GJ5)PXT\n" +
                "YSX)QT6\n" +
                "S74)HHH\n" +
                "2SG)Q63\n" +
                "N81)FGV\n" +
                "6V4)4VC\n" +
                "V12)HTX\n" +
                "SBY)WP6\n" +
                "22S)4JY\n" +
                "18W)CDB\n" +
                "8J6)3YS\n" +
                "BNS)X8W\n" +
                "L9V)N4T\n" +
                "JYL)R3X\n" +
                "941)5N8\n" +
                "8JL)JNJ\n" +
                "GVW)5LF\n" +
                "Z9K)H3K\n" +
                "G1T)MXH\n" +
                "11S)48W\n" +
                "4FX)8BD\n" +
                "NMN)YWJ\n" +
                "SY5)98H\n" +
                "MKT)44B\n" +
                "KNB)73D\n" +
                "GX4)BBP\n" +
                "V4P)8ZS\n" +
                "29S)3ZQ\n" +
                "X1H)MXF\n" +
                "FVC)16Q\n" +
                "TD1)79C\n" +
                "C2W)6HG\n" +
                "KHH)F82\n" +
                "D6R)PHM\n" +
                "C3H)K4T\n" +
                "6TR)NXG\n" +
                "RWV)17F\n" +
                "4ZW)FVY\n" +
                "5JQ)VDX\n" +
                "8XX)34J\n" +
                "VMX)HT3\n" +
                "JCY)X1H\n" +
                "4TN)8XX\n" +
                "QW6)8S9\n" +
                "Y78)87P\n" +
                "7BM)3Z9\n" +
                "8M3)396\n" +
                "RZ2)TLX\n" +
                "68P)41J\n" +
                "C72)3QM\n" +
                "J8D)61B\n" +
                "T3B)HTL\n" +
                "TC7)WQ1\n" +
                "676)CDW\n" +
                "7CW)J2Z\n" +
                "XYJ)68X\n" +
                "6VJ)RJH\n" +
                "CXC)R34\n" +
                "WQ2)WBW\n" +
                "1F2)X2X\n" +
                "QP1)JSJ\n" +
                "7KG)LL2\n" +
                "L63)TKM\n" +
                "RQ5)MV8\n" +
                "MGP)2V4\n" +
                "1LX)TYN\n" +
                "HJ6)LVP\n" +
                "3Z3)JB8\n" +
                "FQT)X7G\n" +
                "7XN)3VH\n" +
                "YWJ)TH8\n" +
                "787)8JV\n" +
                "TWJ)18L\n" +
                "MQT)3RG\n" +
                "XKP)YRQ\n" +
                "KJF)LRW\n" +
                "148)G7L\n" +
                "PR6)9JP\n" +
                "W5Q)GX4\n" +
                "JSJ)9HH\n" +
                "DKP)KXX\n" +
                "Z3Y)TRH\n" +
                "26K)8TS\n" +
                "VKP)XH6\n" +
                "Q9Q)3QH\n" +
                "1ZB)NWD\n" +
                "3KN)G92\n" +
                "64S)BJF\n" +
                "ZRT)KH5\n" +
                "N5M)VW9\n" +
                "142)RG1\n" +
                "V76)B1J\n" +
                "PBC)SY3\n" +
                "H8C)4SH\n" +
                "H78)7SR\n" +
                "2HP)R56\n" +
                "RGX)XB2\n" +
                "SKD)MFJ\n" +
                "7MV)4C5\n" +
                "X9H)LHQ\n" +
                "BBW)RFB\n" +
                "47F)X1V\n" +
                "3SP)DRJ\n" +
                "8KQ)5X5\n" +
                "ZHP)3NM\n" +
                "Z45)BKW\n" +
                "J87)RB4\n" +
                "748)7QG\n" +
                "X2R)QK8\n" +
                "6YN)SV1\n" +
                "6WP)83M\n" +
                "V68)NDS\n" +
                "49Q)SF1\n" +
                "L8D)XH1\n" +
                "HTQ)LWC\n" +
                "M9H)HFB\n" +
                "59W)K9T\n" +
                "FCT)ZTH\n" +
                "SF9)YTP\n" +
                "R63)L3J\n" +
                "SLX)WJD\n" +
                "4FY)YSN\n" +
                "TBR)QHK\n" +
                "615)V2V\n" +
                "B1J)4TN\n" +
                "XZV)GKX\n" +
                "8XX)CXC\n" +
                "FCT)S5M\n" +
                "YND)HTQ\n" +
                "HRC)Z39\n" +
                "Z4N)1TW\n" +
                "3ST)BYW\n" +
                "XHF)YGL\n" +
                "4JY)GVW\n" +
                "QNM)SBG\n" +
                "JVZ)TGZ\n" +
                "VB3)RB7\n" +
                "Z7M)MJL\n" +
                "KGG)Q8D\n" +
                "GYG)8FB\n" +
                "RRS)QF5\n" +
                "P7Y)LF3\n" +
                "MTG)GFJ\n" +
                "LHK)XP3\n" +
                "Z8V)VG3\n" +
                "Y9C)KK1\n" +
                "28L)26K\n" +
                "BX9)RMS\n" +
                "XB1)YQQ\n" +
                "PXF)9V6\n" +
                "4FR)J68\n" +
                "TMN)F2Y\n" +
                "MRX)N16\n" +
                "Y2Q)3QL\n" +
                "Z4Z)S8Y\n" +
                "3DT)VFM\n" +
                "751)L74\n" +
                "FKB)19W\n" +
                "X7B)J8D\n" +
                "C7K)7KG\n" +
                "R46)J37\n" +
                "QM2)FBW\n" +
                "FGS)NG8\n" +
                "PG1)91M\n" +
                "DRJ)175\n" +
                "S9Y)4LG\n" +
                "GX2)VF4\n" +
                "JT5)TQ2\n" +
                "87P)NVS\n" +
                "FLB)CT5\n" +
                "KK2)C3T\n" +
                "Y5J)BXF\n" +
                "S8X)XZ2\n" +
                "J7D)N5M\n" +
                "CLJ)TYC\n" +
                "794)YVG\n" +
                "YCP)DNZ\n" +
                "W9N)4NG\n" +
                "QK8)79Y\n" +
                "MQP)B3G\n" +
                "8F8)9J6\n" +
                "Z8D)PWT\n" +
                "WBW)98G\n" +
                "VX8)625\n" +
                "KSP)CHX\n" +
                "M5Q)J49\n" +
                "RMJ)QGQ\n" +
                "X6K)9T2\n" +
                "YC6)8VT\n" +
                "QT6)NB9\n" +
                "PC8)N38\n" +
                "FCD)2VQ\n" +
                "PCB)BB5\n" +
                "HXN)8C2\n" +
                "NF7)SKF\n" +
                "VV7)1H6\n" +
                "X1V)J4P\n" +
                "GSZ)DWX\n" +
                "QGQ)NKJ\n" +
                "CYV)9P7\n" +
                "94Y)YHV\n" +
                "RZY)JZ6\n" +
                "WXY)Q3L\n" +
                "RJC)T99\n" +
                "RWQ)KX7\n" +
                "RFQ)S6Q\n" +
                "QP1)BWD\n" +
                "KH5)NTV\n" +
                "DDJ)C8J\n" +
                "Z9L)RXZ\n" +
                "7M1)DH9\n" +
                "4JY)XQH\n" +
                "9TY)T59\n" +
                "P34)174\n" +
                "FM8)F25\n" +
                "76Q)81F\n" +
                "9WT)T33\n" +
                "8ZD)GQ7\n" +
                "MZW)1QC\n" +
                "HLW)YWR\n" +
                "H3K)1LX\n" +
                "L7F)1S6\n" +
                "SQB)5LJ\n" +
                "7VV)FXV\n" +
                "Q3L)QHT\n" +
                "34J)1Z3\n" +
                "P2P)FG9\n" +
                "15B)G52\n" +
                "KVS)YRX\n" +
                "5T7)NCC\n" +
                "TGZ)FRG\n" +
                "P7X)YOU\n" +
                "J37)MS5\n" +
                "DL4)DHS\n" +
                "PBH)HFV\n" +
                "KTD)ZHZ\n" +
                "GGH)FQJ\n" +
                "BJF)LWZ\n" +
                "R16)7VV\n" +
                "DQM)KG4\n" +
                "74Z)XYJ\n" +
                "11P)QT3\n" +
                "W1J)R42\n" +
                "Z1B)B8M\n" +
                "PD6)FQT\n" +
                "X1H)QD1\n" +
                "QGR)TX5\n" +
                "TDF)9TM\n" +
                "X11)9L1\n" +
                "P72)SZQ\n" +
                "CYT)1VW\n" +
                "PL9)FXW\n" +
                "HKD)8CP\n" +
                "F5L)G1T\n" +
                "KMV)YX9\n" +
                "1PS)GVG\n" +
                "DL7)W9N\n" +
                "M26)5QL\n" +
                "PLC)FCS\n" +
                "SY3)PZF\n" +
                "JPS)FVG\n" +
                "8BD)DZV\n" +
                "9MB)VCD\n" +
                "WS8)ZJG\n" +
                "9H6)2QY\n" +
                "HYQ)4N9\n" +
                "73D)HX4\n" +
                "6RB)QGV\n" +
                "MT2)GWN\n" +
                "12Q)NX7\n" +
                "KGB)9T4\n" +
                "XRD)M3T\n" +
                "P15)W5Q\n" +
                "JJ8)ZXJ\n" +
                "FXV)94Y\n" +
                "R1J)HTZ\n" +
                "1XP)7CW\n" +
                "ZZ1)X4S\n" +
                "KWG)WSN\n" +
                "RQK)Z9S\n" +
                "1M9)Z74\n" +
                "538)6CK\n" +
                "TN4)5T7\n" +
                "NXV)15S\n" +
                "8Q3)QZH\n" +
                "75N)YFS\n" +
                "VNN)LSC\n" +
                "NZS)L6V\n" +
                "LXN)FPQ\n" +
                "GYS)MZD\n" +
                "XM6)L66\n" +
                "LRG)KSP\n" +
                "CHX)Y7T\n" +
                "SLS)FFX\n" +
                "PP5)QZV\n" +
                "K8W)751\n" +
                "S1C)H2H\n" +
                "H93)WSY\n" +
                "175)ZTN\n" +
                "1F6)HLS\n" +
                "MVN)C79\n" +
                "N5T)LRM\n" +
                "W1P)VHN\n" +
                "G1C)N1W\n" +
                "GBJ)WWJ\n" +
                "KCN)8PX\n" +
                "QRH)6H2\n" +
                "1VW)GGX\n" +
                "J9N)RQL\n" +
                "J6B)YVT\n" +
                "BWD)VQR\n" +
                "JZ6)M4B\n" +
                "Q48)H4K\n" +
                "897)XJN\n" +
                "LSB)PPJ\n" +
                "5HK)KDQ\n" +
                "DL2)1TD\n" +
                "NSS)YVV\n" +
                "QVF)ZVV\n" +
                "BJF)WQ2\n" +
                "JTQ)62Q\n" +
                "765)N4P\n" +
                "H65)YMK\n" +
                "3JV)3NL\n" +
                "QQL)NZS\n" +
                "ZW2)V3C\n" +
                "FVC)97Z\n" +
                "ZSP)L71\n" +
                "J66)NTN\n" +
                "DY4)M2G\n" +
                "W5B)SKN\n" +
                "4G7)676\n" +
                "F21)C67\n" +
                "TCT)6FW\n" +
                "4TT)YR3\n" +
                "468)WXH\n" +
                "HDP)PG1\n" +
                "X79)NQK\n" +
                "S2J)BD6\n" +
                "2CG)SDJ\n" +
                "PZF)QFW\n" +
                "HX4)5JQ\n" +
                "SCP)CB8\n" +
                "XWJ)D47\n" +
                "CSX)V12\n" +
                "T99)B11\n" +
                "272)3F5\n" +
                "96V)M26\n" +
                "4SH)W3P\n" +
                "DF2)8N9\n" +
                "8CP)CWX\n" +
                "2T8)PF3\n" +
                "XH6)36Q\n" +
                "8N9)5XN\n" +
                "WXH)L6N\n" +
                "YZ8)L5W\n" +
                "6FW)GCH\n" +
                "S2V)CQP\n" +
                "Y11)WMK\n" +
                "Q48)F4X\n" +
                "N4P)ZHL\n" +
                "7HX)VLK\n" +
                "Q7Y)JRB\n" +
                "HL3)1ZD\n" +
                "ZQD)DKP\n" +
                "9H6)SAN\n" +
                "BB5)7BK\n" +
                "SKD)DYX\n" +
                "QDZ)ZK8\n" +
                "ZH6)1JC\n" +
                "GVT)P91\n" +
                "VLT)WXY\n" +
                "DH9)WDW\n" +
                "SP6)SSY\n" +
                "MTZ)GQ8\n" +
                "RJH)468\n" +
                "YC1)15B\n" +
                "FGV)MRX\n" +
                "8FB)LCW\n" +
                "F25)6Q4\n" +
                "424)SCL\n" +
                "WZG)JXW\n" +
                "396)XRX\n" +
                "JWC)F74\n" +
                "NZS)L75\n" +
                "C6B)9N9\n" +
                "34J)HKD\n" +
                "MZJ)LSF\n" +
                "S2T)4G7\n" +
                "X15)R16\n" +
                "ZH5)XPL\n" +
                "6VV)3ZK\n" +
                "55F)DDJ\n" +
                "PC6)4HG\n" +
                "N7B)897\n" +
                "V61)82Q\n" +
                "MS5)86B\n" +
                "16J)ZKZ\n" +
                "HVX)941\n" +
                "M2G)ZPB\n" +
                "PWC)NPH\n" +
                "FC1)Q48\n" +
                "9FZ)PVJ\n" +
                "R77)KRV\n" +
                "V6Q)SLS\n" +
                "5HB)6TR\n" +
                "3YS)2ZF\n" +
                "3TV)K9H\n" +
                "M18)QNM\n" +
                "3P6)GCC\n" +
                "SXM)6HS\n" +
                "4VD)T5N\n" +
                "6G1)H8H\n" +
                "7GG)R2D\n" +
                "5LJ)ZSP\n" +
                "6DB)NKT\n" +
                "B6T)73R\n" +
                "FH5)GVT\n" +
                "8SP)Z45\n" +
                "YSY)QQ7\n" +
                "9TM)MQP\n" +
                "2YZ)GT7\n" +
                "5X3)DF4\n" +
                "8TK)JLD\n" +
                "4N9)VKP\n" +
                "9T2)CNG\n" +
                "FDC)B6S\n" +
                "91X)TKQ\n" +
                "86H)HXZ\n" +
                "2TG)JPT\n" +
                "YVG)9JM\n" +
                "YTN)S95\n" +
                "RTD)C3H\n" +
                "625)73C\n" +
                "JRB)1XP\n" +
                "SX7)JWC\n" +
                "TSD)RP6\n" +
                "5X5)RSN\n" +
                "LLL)Y2Q\n" +
                "NQK)TSZ\n" +
                "H73)19D\n" +
                "C6B)ZQD\n" +
                "PPJ)VKR\n" +
                "FK4)XF9\n" +
                "XM2)2LK\n" +
                "67Z)95V\n" +
                "D3M)997\n" +
                "QFW)R1J\n" +
                "G1T)F37\n" +
                "KY9)R46\n" +
                "1RF)6RB\n" +
                "TDQ)34D\n" +
                "3QJ)MTR\n" +
                "VKR)49P\n" +
                "G57)DM1\n" +
                "Q73)TTR\n" +
                "LKY)6V4\n" +
                "B11)DPL\n" +
                "8QD)248\n" +
                "GFJ)MVN\n" +
                "MNQ)XRD\n" +
                "LXS)QXK\n" +
                "MFG)WD2\n" +
                "JTJ)3WX\n" +
                "2V4)8G5\n" +
                "H2T)3JC\n" +
                "MRD)QHM\n" +
                "HT5)JNP\n" +
                "HSZ)2Z2\n" +
                "YGL)QK7\n" +
                "SJF)VMX\n" +
                "X4Y)8K7\n" +
                "LGG)MJS\n" +
                "K8Q)VBQ\n" +
                "QT8)NSS\n" +
                "377)ZHP\n" +
                "SM6)MRD\n" +
                "XYL)YM4\n" +
                "3H8)LPT\n" +
                "6QH)B9M\n" +
                "QX5)9SB\n" +
                "F1S)9QR\n" +
                "42W)PKW\n" +
                "Z9S)QD2\n" +
                "R34)CLJ\n" +
                "KK1)Z23\n" +
                "XZ2)6VV\n" +
                "3VH)P2P\n" +
                "3F3)FGS\n" +
                "CWX)WWQ\n" +
                "JJ8)BFH\n" +
                "D5F)91Y\n" +
                "S15)2T8\n" +
                "GKD)1W1\n" +
                "GPD)6MM\n" +
                "2XH)Y77\n" +
                "4JH)R95\n" +
                "H8H)3KD\n" +
                "YF5)TG1\n" +
                "WCG)F63\n" +
                "67Z)9RD\n" +
                "73R)C7Z\n" +
                "B88)7BX\n" +
                "HHH)7B9\n" +
                "NKJ)ZPM\n" +
                "WLQ)JG2\n" +
                "P5Q)GHN\n" +
                "C3B)F46\n" +
                "8CL)26T\n" +
                "N4T)46R\n" +
                "YKT)89V\n" +
                "6RF)D3M\n" +
                "R2F)18W\n" +
                "X4H)DL4\n" +
                "XRX)FCD\n" +
                "YFC)WGZ\n" +
                "LRM)6RF\n" +
                "3CH)XQT\n" +
                "PVJ)SNV\n" +
                "H9M)H2V\n" +
                "15T)8QD\n" +
                "J68)RWV\n" +
                "XFH)VB3\n" +
                "GVW)9SQ\n" +
                "T8F)KFW\n" +
                "QT5)BXJ\n" +
                "K6C)3DZ\n" +
                "SBG)Y1X\n" +
                "N69)7HX\n" +
                "V86)314\n" +
                "GTJ)D6R\n" +
                "V3C)CJS\n" +
                "9S1)6GD\n" +
                "86B)X5L\n" +
                "P69)QRW\n" +
                "R8C)BWZ\n" +
                "FXD)1PM\n" +
                "TSG)Y78\n" +
                "G9G)4Y9\n" +
                "9LV)1F2\n" +
                "K66)YDF\n" +
                "RG1)F1X\n" +
                "VGL)3KN\n" +
                "RFB)Z4Z\n" +
                "66P)L6D\n" +
                "6G9)YFL\n" +
                "NWR)PD3\n" +
                "L6D)CB3\n" +
                "V5J)C6B\n" +
                "C67)3PJ\n" +
                "B6X)S9Y\n" +
                "9TY)JVZ\n" +
                "8ZS)H2T\n" +
                "J2Z)4JH\n" +
                "QHT)V87\n" +
                "8JV)PZP\n" +
                "VYM)K1M\n" +
                "WSY)YSH\n" +
                "C83)242\n" +
                "TDM)LR9\n" +
                "RRS)LJ2\n" +
                "VDX)GQ2\n" +
                "PLT)76Q\n" +
                "PBC)142\n" +
                "1QC)F1V\n" +
                "DSJ)SXF\n" +
                "YSK)S2T\n" +
                "KJF)QDZ\n" +
                "LSC)XT3\n" +
                "XKK)HRK\n" +
                "YRQ)SR9\n" +
                "Q39)449\n" +
                "216)K8Z\n" +
                "B16)RFZ\n" +
                "34N)G29\n" +
                "2ZF)H8N\n" +
                "S6Q)G4H\n" +
                "B75)X79\n" +
                "LRW)8J5\n" +
                "NCK)5B3\n" +
                "3DZ)RMW\n" +
                "MHM)22S\n" +
                "Y5N)88G\n" +
                "H4R)8NZ\n" +
                "6GB)R2P\n" +
                "97Y)Y37\n" +
                "X3G)F79\n" +
                "JJ1)6RW\n" +
                "HXZ)N5T\n" +
                "YFL)3P6\n" +
                "QMV)PBC\n" +
                "9RD)6DG\n" +
                "SDJ)16J\n" +
                "DNZ)7WN\n" +
                "MZD)J92\n" +
                "YSH)GX2\n" +
                "VNG)4DR\n" +
                "LPM)3YD\n" +
                "JB8)WZG\n" +
                "4T7)8RK\n" +
                "FQJ)FTT\n" +
                "ZPM)PRX\n" +
                "F46)LDN\n" +
                "PF3)LRZ\n" +
                "6RW)MNQ\n" +
                "9GN)CGW\n" +
                "LVP)N7D\n" +
                "VJS)P72\n" +
                "Y7R)N3N\n" +
                "DY4)1P1\n" +
                "CMQ)HX3\n" +
                "CB3)V5N\n" +
                "JJ6)58Y\n" +
                "ZXJ)W5B\n" +
                "4LH)7MV\n" +
                "DVN)34N\n" +
                "GD3)2BR\n" +
                "CVP)51P\n" +
                "CQP)KJW\n" +
                "LCB)Z9L\n" +
                "JZH)S67\n" +
                "K9T)MPT\n" +
                "L9J)Z6N\n" +
                "WRV)SRR\n" +
                "V9Y)5QH\n" +
                "J59)CGN\n" +
                "17F)DH2\n" +
                "B3G)VBC\n" +
                "TSH)JKN\n" +
                "H7L)9D8\n" +
                "6MV)7HT\n" +
                "BYK)MKT\n" +
                "V8V)WCG\n" +
                "COM)WLQ\n" +
                "939)Z42\n" +
                "BSS)459\n" +
                "TQ2)L9J\n" +
                "KSC)K6X\n" +
                "F37)K6Q\n" +
                "H9D)V5J\n" +
                "SBC)FWX\n" +
                "FNX)T3B\n" +
                "1WV)8Z5\n" +
                "MB5)CVY\n" +
                "TY5)794\n" +
                "PWT)QWS\n" +
                "XHC)RZ2\n" +
                "BFH)S15\n" +
                "S21)41Q\n" +
                "TP2)GDF\n" +
                "P91)M93\n" +
                "TBF)6QK\n" +
                "8HW)YSK\n" +
                "459)8D4\n" +
                "FWV)5JP\n" +
                "9CB)7HZ\n" +
                "WJL)FP7\n" +
                "RY6)T39\n" +
                "8D4)972\n" +
                "N38)PCB\n" +
                "SV1)R2F\n" +
                "JJQ)H3M\n" +
                "6YN)R6D\n" +
                "YGQ)H8K\n" +
                "5NV)LMY\n" +
                "7LV)CDH\n" +
                "12P)2TG\n" +
                "JBS)3JV\n" +
                "Q5P)V86\n" +
                "GFD)2X7\n" +
                "6FQ)2YZ\n" +
                "8NZ)BQP\n" +
                "8HG)3YK\n" +
                "RP6)MFP\n" +
                "7W2)SP6\n" +
                "T8Z)PC8\n" +
                "126)LQJ\n" +
                "2KK)Y11\n" +
                "BY5)VXS\n" +
                "FPQ)QP1\n" +
                "396)F9Y\n" +
                "4D9)4T7\n" +
                "29R)V9S\n" +
                "GBJ)VNF\n" +
                "ZBK)ZH5\n" +
                "QZV)4YL\n" +
                "GRV)3W4\n" +
                "3BT)PRQ\n" +
                "WSN)8X5\n" +
                "QZH)Y9G\n" +
                "VQR)YX3\n" +
                "KJ1)QX5\n" +
                "XXV)2XH\n" +
                "91Y)TCT\n" +
                "YQ3)X6K\n" +
                "M93)5HK\n" +
                "BQL)4VJ\n" +
                "R3X)HNW\n" +
                "9X1)TC7\n" +
                "298)V9Y\n" +
                "MFD)KNB\n" +
                "MFP)YTN\n" +
                "K8H)4D9\n" +
                "FWX)QGM\n" +
                "LF4)2WW\n" +
                "X6J)S54\n" +
                "J4P)FVC\n" +
                "PHQ)6WP\n" +
                "18R)QRH\n" +
                "3YD)NYX\n" +
                "73C)BW2\n" +
                "CB8)QHY\n" +
                "R6R)FWV\n" +
                "DS4)S1X\n" +
                "F9Y)ZRT\n" +
                "Z5M)H85\n" +
                "SR9)9LV\n" +
                "NK4)GQM\n" +
                "F87)9X1\n" +
                "8G5)YTH\n" +
                "9LV)7PN\n" +
                "5Y3)WSS\n" +
                "9JP)5T2\n" +
                "GHN)6NJ\n" +
                "G11)BGM\n" +
                "D8Y)PHQ\n" +
                "MGV)VRF\n" +
                "N7D)787\n" +
                "27Z)X6J\n" +
                "FFX)F3S\n" +
                "68X)67Z\n" +
                "MT2)XFH\n" +
                "YCZ)HX2\n" +
                "ZCX)25Q\n" +
                "CBK)ZBK\n" +
                "RBP)6GW\n" +
                "R6N)TY5\n" +
                "MTG)DL7\n" +
                "CFN)DL2\n" +
                "X7G)9C8\n" +
                "XQT)YFC\n" +
                "CWY)G7H\n" +
                "VF4)XKP\n" +
                "169)WSX\n" +
                "Z95)54H\n" +
                "ZHB)JX1\n" +
                "9JP)CVP\n" +
                "1P8)LPM\n" +
                "F7G)7QW\n" +
                "VBQ)291\n" +
                "XB2)8TL\n" +
                "5N8)HRL\n" +
                "3NL)7GR\n" +
                "R56)YFD\n" +
                "7BK)RGB\n" +
                "89V)LGG\n" +
                "TNF)86Z\n" +
                "H2H)HSZ\n" +
                "CT5)T5L\n" +
                "5KF)83R\n" +
                "SKN)XTV\n" +
                "HTX)SQV\n" +
                "9T4)5B9\n" +
                "4Z9)PD6\n" +
                "1ZD)HPG\n" +
                "PHP)DFB\n" +
                "31H)XDY\n" +
                "9KZ)47S\n" +
                "KW1)FCT\n" +
                "VW9)4QL\n" +
                "1KW)MHM\n" +
                "PRQ)V1B\n" +
                "D52)72Q\n" +
                "8Y1)21R\n" +
                "HT3)ZVN\n" +
                "LWC)748\n" +
                "3ZQ)84V\n" +
                "53F)Q83\n" +
                "YX3)BYK\n" +
                "4Y9)5SY\n" +
                "PLT)TKF\n" +
                "YFS)LSB\n" +
                "RMW)97Y\n" +
                "1W1)HJ6\n" +
                "SJN)28L\n" +
                "XYJ)8KQ\n" +
                "G86)X8Y\n" +
                "1GD)K2Y\n" +
                "ZPB)5DY\n" +
                "QQD)FKD\n" +
                "B8M)7YC\n" +
                "F4X)CVL\n" +
                "15S)MGP\n" +
                "B19)HK8\n" +
                "WG7)7XJ\n" +
                "JWF)7BM\n" +
                "86Z)126\n" +
                "QQ7)6YN\n" +
                "9GN)KZH\n" +
                "J52)HXN\n" +
                "GGM)68P\n" +
                "SVQ)LXS\n" +
                "F1V)B5L\n" +
                "7B9)YW5\n" +
                "3PP)YW3\n" +
                "RSP)Z3F\n" +
                "8K7)216\n" +
                "8F8)KGG\n" +
                "WRQ)GZM\n" +
                "91M)ZW2\n" +
                "VLK)LLL\n" +
                "Z6N)TDJ\n" +
                "FTT)T3H\n" +
                "CH5)KHH\n" +
                "GQM)T3Z\n" +
                "8C2)6F7\n" +
                "JG3)BDB\n" +
                "L75)J2C\n" +
                "1S8)ZN9\n" +
                "XDL)C2W\n" +
                "JX1)BBW\n" +
                "FG9)D5F\n" +
                "P2G)3NQ\n" +
                "2WW)SMS\n" +
                "9C8)CWY\n" +
                "3QX)7GJ\n" +
                "SG8)H9D\n" +
                "KFW)VD6\n" +
                "LWZ)BSS\n" +
                "SWY)K8H\n" +
                "F1X)Q5P\n" +
                "9SQ)J6B\n" +
                "WF6)F57\n" +
                "5SK)FXD\n" +
                "34D)41H\n" +
                "6DB)2LC\n" +
                "M9Z)4LH\n" +
                "FXR)KVS\n" +
                "9MJ)15P\n" +
                "B9F)9TY\n" +
                "M4L)QQL\n" +
                "Q63)PLC\n" +
                "6ZC)6VJ\n" +
                "N16)W1B\n" +
                "6SX)3QX\n" +
                "7WZ)N8H\n" +
                "974)K66\n" +
                "3BZ)FLB\n" +
                "T3Z)VLT\n" +
                "2DS)BQL\n" +
                "61B)SY5\n" +
                "TKQ)BFP\n" +
                "3NM)H6G\n" +
                "M25)N81\n" +
                "XKB)H32\n" +
                "ZXH)LJC\n" +
                "8Z5)KSC\n" +
                "5XN)6Z7\n" +
                "36Q)FXR\n" +
                "2LC)SJF\n" +
                "T1J)CYV\n" +
                "SWM)Z7M\n" +
                "RZ2)P34\n" +
                "Y9C)15T\n" +
                "MKW)SF8\n" +
                "J94)TN4\n" +
                "DV8)SWH\n" +
                "JJ1)DMS\n" +
                "BL1)4TS\n" +
                "ZCR)55F\n" +
                "G79)4PS\n" +
                "T5L)XWJ\n" +
                "BYW)B88\n" +
                "3D5)25D\n" +
                "CPZ)1GS\n" +
                "524)59W\n" +
                "J2C)Y9C\n" +
                "R13)R6N\n" +
                "9D8)1S7\n" +
                "ZVX)1ZB\n" +
                "VNS)ZZS\n" +
                "DM1)BNG\n" +
                "CVY)GTJ\n" +
                "GQ2)BL1\n" +
                "8HL)NSQ\n" +
                "PNS)96R\n" +
                "G4H)QFX\n" +
                "DFB)TDQ\n" +
                "S5M)PFD\n" +
                "TH8)SLX\n" +
                "BX6)XYL\n" +
                "V5F)LLF\n" +
                "41Q)1YG\n" +
                "1GP)SL7\n" +
                "W52)6G1\n" +
                "4C5)H8Z\n" +
                "KG4)86H\n" +
                "7GR)387\n" +
                "KNY)CQ1\n" +
                "HCJ)3JW\n" +
                "2K2)J87\n" +
                "916)LKY\n" +
                "RNL)YQM\n" +
                "WSS)3BZ\n" +
                "LH1)PR6\n" +
                "SWH)7TS\n" +
                "Z42)R4S\n" +
                "C2R)JJ1\n" +
                "GCH)TVW\n" +
                "B9F)8J6\n" +
                "9TW)9MJ\n" +
                "KDQ)QW6\n" +
                "ZFC)GXX\n" +
                "4ZM)T1R\n" +
                "VG3)PNS\n" +
                "DHS)LMX\n" +
                "5JZ)D9Z\n" +
                "YTP)8SX\n" +
                "S41)6FQ\n" +
                "1S7)KL9\n" +
                "YHV)W52\n" +
                "96R)RR6\n" +
                "YW5)54D\n" +
                "5CJ)3TV\n" +
                "RFZ)NMN\n" +
                "QF5)WF6\n" +
                "3TW)MTZ\n" +
                "DHD)KYT\n" +
                "2X7)SG8\n" +
                "YW5)RJC\n" +
                "NMC)8HG\n" +
                "74N)RNG\n" +
                "ZKZ)878\n" +
                "8HG)QVF\n" +
                "JYD)FK4\n" +
                "972)PQJ\n" +
                "248)TWN\n" +
                "SQV)P6Q\n" +
                "TLX)8J9\n" +
                "VCD)YCP\n" +
                "BDB)C72\n" +
                "7MV)C3B\n" +
                "QBG)GD3\n" +
                "F74)41K\n" +
                "2SV)5TL\n" +
                "TCR)GWQ\n" +
                "G7M)PXZ\n" +
                "ZVV)W1J\n" +
                "GX1)5CJ\n" +
                "N8H)WRV\n" +
                "25D)B75\n" +
                "MK9)YND\n" +
                "VFZ)M9Z\n" +
                "RH1)X4Y\n" +
                "FJW)BD2\n" +
                "M1V)GKD\n" +
                "41J)DY4\n" +
                "3ZK)MFG\n" +
                "TQQ)HPT\n" +
                "T84)5X3\n" +
                "KHR)MJ7\n" +
                "Q5L)NH7\n" +
                "YQM)5HB\n" +
                "4DR)9JS\n" +
                "JGL)8W3\n" +
                "Y7T)P7X\n" +
                "G6R)RL3\n" +
                "PXT)P4V\n" +
                "M18)M1V\n" +
                "YRX)FM8\n" +
                "84V)2CG\n" +
                "WD2)DYW\n" +
                "8J9)L72\n" +
                "R2V)PQG\n" +
                "64D)27Z\n" +
                "5KD)76Z\n" +
                "HPG)5JM\n" +
                "XP3)BX9\n" +
                "HPT)BX6\n" +
                "C7Z)5QP\n" +
                "ZJG)5SG\n" +
                "H2V)75N\n" +
                "H47)4WS\n" +
                "VCM)43R\n" +
                "5TJ)49Q\n" +
                "VRF)N43\n" +
                "T1R)PC6\n" +
                "HWT)B9F\n" +
                "16Q)Q39\n" +
                "HQF)3QJ\n" +
                "CLH)V61\n" +
                "25D)1M3\n" +
                "QQ1)LPQ\n" +
                "HPP)SN4\n" +
                "CQ1)DHD\n" +
                "XQH)SXM\n" +
                "W1B)RGX\n" +
                "4HG)YQ3\n" +
                "77Y)NF7\n" +
                "15P)K3H\n" +
                "FQ9)SF9\n" +
                "Y75)S2V\n" +
                "NVS)YKT\n" +
                "7HZ)X5X\n" +
                "8TT)F1S\n" +
                "PYC)PS7\n" +
                "WJQ)272\n" +
                "5B9)169\n" +
                "HZR)ZMY\n" +
                "7M1)5FK\n" +
                "665)CLH\n" +
                "S1X)HPP\n" +
                "S95)N3Y\n" +
                "LGF)KWG\n" +
                "NYX)Z5X\n" +
                "98G)R6R\n" +
                "WJD)K3T\n" +
                "YFD)XQF\n" +
                "Z23)4ZW\n" +
                "RSN)9H6\n" +
                "YWJ)PMD\n" +
                "M83)8M3\n" +
                "1TW)DSJ\n" +
                "RSP)LD3\n" +
                "XF3)XRN\n" +
                "JG2)HRC\n" +
                "DYX)SM6\n" +
                "FTB)9S1\n" +
                "83M)9JR\n" +
                "3NL)XPT\n" +
                "9V6)47F\n" +
                "D5K)SLV\n" +
                "BPP)M83\n" +
                "SY7)SX7\n" +
                "1LM)7GG\n" +
                "P8H)2CQ\n" +
                "3M3)4ZB\n" +
                "41K)3PP\n" +
                "KZH)9Q9\n" +
                "MZW)LCB\n" +
                "TG1)CBK\n" +
                "242)YSX\n" +
                "LRZ)PY6\n" +
                "TRH)RMJ\n" +
                "2NC)XWY\n" +
                "5QH)TH7\n" +
                "QNY)9WT\n" +
                "TSZ)JJQ\n" +
                "G7H)VFZ\n" +
                "Y51)ZCK\n" +
                "QGM)63Z\n" +
                "Q92)VNG\n" +
                "NX7)HL3\n" +
                "K2Y)NNM\n" +
                "CGW)N3F\n" +
                "CBK)YGQ\n" +
                "HL2)SJX\n" +
                "921)PLT\n" +
                "B1J)7XN\n" +
                "47S)Y51\n" +
                "PZP)FNX\n" +
                "DMS)H7L\n" +
                "KN8)MZW\n" +
                "DDF)X4H\n" +
                "4VQ)N3H\n" +
                "174)F7H\n" +
                "L72)6MV\n" +
                "XDR)CCR\n" +
                "WQ1)QGR\n" +
                "NSQ)7CN\n" +
                "PQJ)8B5\n" +
                "CDQ)GYT\n" +
                "YQQ)91X\n" +
                "5NZ)DF2\n" +
                "14H)8YB\n" +
                "7N9)MJW\n" +
                "3XT)JQM\n" +
                "5LD)TW3\n" +
                "4WS)ZVX\n" +
                "PWT)2KN\n" +
                "8S9)96V\n" +
                "ZHZ)1FJ\n" +
                "BC4)X6G\n" +
                "MGT)75P\n" +
                "HX3)Z8D\n" +
                "7CN)Y4J\n" +
                "C83)TQQ\n" +
                "PFD)R2V\n" +
                "H3M)PWC\n" +
                "8ZD)8F8\n" +
                "TYN)1GD\n" +
                "HFV)TDM\n" +
                "Y37)F21\n" +
                "XFD)5JF\n" +
                "Q9X)Z5V\n" +
                "YM4)VNN\n" +
                "MRG)HZR\n" +
                "GZV)Q7Y\n" +
                "GZM)3Z3\n" +
                "997)9MB\n" +
                "KL9)3M3\n" +
                "XTV)JT5\n" +
                "HTR)GFD\n" +
                "SLK)NB7\n" +
                "MPT)1M9\n" +
                "449)KN8\n" +
                "MJW)MTV\n" +
                "ZVN)7W2\n" +
                "21R)BD3\n" +
                "HK8)NCK\n" +
                "FBW)D41\n" +
                "L71)39K\n" +
                "YR3)Z8V\n" +
                "LSF)KK2\n" +
                "MTV)1F6\n" +
                "387)T84\n" +
                "6Q4)VJS\n" +
                "R2D)VPQ\n" +
                "DWX)3BT\n" +
                "KSV)6L7\n" +
                "CXK)GNT\n" +
                "81F)974\n" +
                "LDN)WRW\n" +
                "FRG)K8Q\n" +
                "54H)8L3\n" +
                "KXV)JGL\n" +
                "BXJ)765\n" +
                "CGN)179\n" +
                "72Q)J9N\n" +
                "W1S)XDR\n" +
                "41Q)ZCR\n" +
                "ZLH)MB5\n" +
                "RXZ)P2G\n" +
                "TYC)X7K\n" +
                "TYS)939\n" +
                "5T6)Y5N\n" +
                "QGR)TWJ\n" +
                "765)1RF\n" +
                "179)GBJ\n" +
                "HTZ)SVQ\n" +
                "2KV)XJD\n" +
                "MVZ)M4L\n" +
                "WP6)1QH\n" +
                "8X5)R63\n" +
                "QT3)R77\n" +
                "QQL)V8V\n" +
                "RR6)77Y\n" +
                "GXX)Y5J\n" +
                "6ZR)Z95\n" +
                "TWN)G57\n" +
                "ZZS)R8C\n" +
                "PMD)WS8\n" +
                "8TL)LB7\n" +
                "QHK)TYS\n" +
                "PMR)8JL\n" +
                "142)TCR\n" +
                "R95)ZFC\n" +
                "6HS)615\n" +
                "5TL)L7F\n" +
                "FP7)LKN\n" +
                "F79)X9H\n" +
                "XWY)4C2\n" +
                "SN4)DWH\n" +
                "1H6)KY9\n" +
                "7QW)XM6\n" +
                "C3T)9TS\n" +
                "XHT)GPX\n" +
                "Q83)GZV\n" +
                "7XJ)MVG\n" +
                "NKT)NKZ\n" +
                "2NX)3CH\n" +
                "T3H)KW1\n" +
                "YHY)K71\n" +
                "GDF)V7L\n" +
                "NLP)DF1\n" +
                "2LK)HDP\n" +
                "L66)V4P\n" +
                "NP9)W8B\n" +
                "49P)SQB\n" +
                "S67)Z1B\n" +
                "YDP)6ZC\n" +
                "7HT)PYY\n" +
                "GQ7)YST\n" +
                "Z39)FKB\n" +
                "QGV)JWF\n" +
                "86B)KXJ\n" +
                "TX5)VX8\n" +
                "V5N)GCW\n" +
                "7BX)JJ8\n" +
                "GT7)3F3\n" +
                "CNG)7M1\n" +
                "58Y)MTG\n" +
                "685)1FR\n" +
                "5SG)H8C\n" +
                "JXW)BZ4\n" +
                "XF9)QQD\n" +
                "CH5)F7G\n" +
                "1YG)KXV\n" +
                "BD2)F5L\n" +
                "NH7)3DT\n" +
                "LQJ)4VD\n" +
                "4ZB)12R\n" +
                "V7P)9FZ\n" +
                "TDJ)M5V\n" +
                "9SB)QBG\n" +
                "BPP)X11\n" +
                "ZKM)3XT\n" +
                "XFJ)54R\n" +
                "NG2)42W\n" +
                "G92)G7V\n" +
                "SJN)XHT\n" +
                "3KD)BLB\n" +
                "8W3)Z4Q\n" +
                "1M3)148\n" +
                "VYM)TSG\n" +
                "4TS)QT5\n" +
                "RFW)T8Z\n" +
                "WWQ)Z5M\n" +
                "TK8)C83\n" +
                "QWS)SY7\n" +
                "SYR)6G9\n" +
                "HNW)P15\n" +
                "PHM)74Z\n" +
                "D1L)FQ9\n" +
                "F82)8Y1\n" +
                "1P1)5LD\n" +
                "6F7)V9W\n" +
                "GPX)H47\n" +
                "MKF)JCY\n" +
                "V76)HL2\n" +
                "G2T)N9W\n" +
                "VPQ)B6X\n" +
                "ZMY)3L1\n" +
                "GCW)HLW\n" +
                "TW3)6DB\n" +
                "H7B)MFL\n" +
                "RQL)CV9\n" +
                "GKX)YF5\n" +
                "89B)3H8\n" +
                "9QR)YHY\n" +
                "K4T)SS1\n" +
                "SZM)GRV\n" +
                "SKF)D5K\n" +
                "6CK)1WV\n" +
                "8RK)8TT\n" +
                "6RB)T1J\n" +
                "X84)7N9\n" +
                "ZN9)9F4\n" +
                "N3F)P73\n" +
                "4V8)4M8\n" +
                "HRK)MKR\n" +
                "CJ4)7N5\n" +
                "HMK)XHF\n" +
                "928)ZT7\n" +
                "Y11)PBH\n" +
                "WMK)843\n" +
                "P73)2ZM\n" +
                "PQG)D8H\n" +
                "RFW)GX1\n" +
                "6GD)8ZD\n" +
                "298)4V8\n" +
                "3X8)CJ4\n" +
                "RR6)7SS\n" +
                "LPT)SJN\n" +
                "7BX)V76\n" +
                "LW2)2TK\n" +
                "DWH)D1L\n" +
                "KLR)XKB\n" +
                "2YZ)WG7\n" +
                "LPQ)FG1\n" +
                "D9Z)TJV\n" +
                "Y9G)XFJ\n" +
                "Z5X)8R6\n" +
                "5FK)M25\n" +
                "LCW)TXX\n" +
                "JKN)685\n" +
                "YTH)QS7\n" +
                "D47)MRG\n" +
                "QW4)9B6\n" +
                "7GJ)XFD\n" +
                "39K)RLD\n" +
                "Z74)5KD\n" +
                "1MD)JPS\n" +
                "8SX)VV7\n" +
                "N9V)V68\n" +
                "TDJ)G86\n" +
                "M9F)XMF\n" +
                "DYW)GGH\n" +
                "B9Z)KTD\n" +
                "HTZ)RY6\n" +
                "K9H)Q9Q\n" +
                "YVT)SYR\n" +
                "FKD)B42\n" +
                "R9N)48L\n" +
                "XPW)BPP\n" +
                "V7L)RFQ\n" +
                "X5X)VV5\n" +
                "XPL)H4R\n" +
                "2TK)WD6\n" +
                "XJD)N45\n" +
                "LV4)S2J\n" +
                "878)TJ4\n" +
                "T59)JYL\n" +
                "S8Y)3X8\n" +
                "ZJG)QM2\n" +
                "FBZ)J7D\n" +
                "3L1)S8X\n" +
                "TNF)35T\n" +
                "83X)BY5\n" +
                "3X8)921\n" +
                "BDD)KCN\n" +
                "TVW)TBR\n" +
                "9HH)CFN\n" +
                "P4V)KV6\n" +
                "BBP)Z5Q\n" +
                "WJ8)G79\n" +
                "KX7)SWY\n" +
                "6ZK)GF8\n" +
                "W3P)H7B\n" +
                "B42)LGF\n" +
                "R3K)J66\n" +
                "WD6)VGF\n" +
                "T5N)CDQ\n" +
                "1XP)1KW\n" +
                "H8N)G2T\n" +
                "BRF)ZCX\n" +
                "FXW)P8H\n" +
                "BGM)H73\n" +
                "QHM)MGV\n" +
                "V87)298\n" +
                "314)5PX\n" +
                "MJL)PR3\n" +
                "GXD)XM2\n" +
                "F7H)K44\n" +
                "JSP)62V\n" +
                "H8C)Z3Y\n" +
                "3RG)6ZK\n" +
                "L3J)DTX\n" +
                "JT5)T8F\n" +
                "XKG)N4S\n" +
                "HX2)XDL\n" +
                "DZV)ZJR\n" +
                "RLD)Q9B\n" +
                "Y1X)XHC\n" +
                "WQ4)JK8\n" +
                "BNG)SLK\n" +
                "LB7)LV4\n" +
                "35T)2NC\n" +
                "GCH)JTJ\n" +
                "K4V)D7G\n" +
                "LF3)7LV\n" +
                "HFB)GYS\n" +
                "4YL)2DS\n" +
                "VBC)SSR\n" +
                "SLV)ZHB\n" +
                "56P)LJ9\n" +
                "62Q)NBX\n" +
                "GYT)GXD\n" +
                "2Z2)CPZ\n" +
                "V61)CMQ\n" +
                "ZC5)RWQ\n" +
                "R9N)NXV\n" +
                "425)LRG\n" +
                "1Z3)Y75\n" +
                "TJV)BQ7\n" +
                "LLF)HCJ\n" +
                "CJS)425\n" +
                "K6Q)4K1\n" +
                "HTX)RNL\n" +
                "9KZ)7D7\n" +
                "FG1)DDF\n" +
                "1RF)FBZ\n" +
                "KXJ)CY9\n" +
                "4HT)J52\n" +
                "R95)B9Z\n" +
                "3NQ)JBS\n" +
                "PPJ)15N\n" +
                "SJX)P69\n" +
                "4PS)64D\n" +
                "H8K)2SV\n" +
                "6DG)5NZ\n" +
                "3Z9)12P\n" +
                "SL7)G1C\n" +
                "5QP)JYD\n" +
                "T39)SWM\n" +
                "95V)29S\n" +
                "NWD)LXN\n" +
                "G29)JTQ\n" +
                "8YB)424\n" +
                "LJ9)ZMG\n" +
                "VXS)WTB\n" +
                "YX9)4FR\n" +
                "WSX)85M\n" +
                "QBG)FJW\n" +
                "DLF)56P\n" +
                "QNM)YSY\n" +
                "9TS)SPR\n" +
                "J49)KGB\n" +
                "3QL)R13\n" +
                "K3T)J2T\n" +
                "PYY)4VQ\n" +
                "K5Y)MT2\n" +
                "RMS)3CM\n" +
                "ZJ8)NWR\n" +
                "V2V)VNS\n" +
                "TC7)89B\n" +
                "26T)5TN\n" +
                "JK8)YC7\n" +
                "P4V)L8S\n" +
                "44B)RQ5\n" +
                "8J5)WJQ\n" +
                "1S6)HVX\n" +
                "H87)7TF\n" +
                "3WX)RBP\n" +
                "RB7)LHK\n" +
                "MJ7)ZC5\n" +
                "2QY)CH5\n" +
                "25Q)1D2\n" +
                "K2Y)2KK\n" +
                "GGM)66P\n" +
                "97Z)YCZ\n" +
                "NTV)4FY\n" +
                "G49)G7M\n" +
                "SXF)8N6\n" +
                "MXF)DLF\n" +
                "T5L)6ZR\n" +
                "878)N7B\n" +
                "5B9)QJT\n" +
                "SZQ)3SP\n" +
                "C8J)XJC\n" +
                "N43)YZ8\n" +
                "9F4)DS4\n" +
                "75P)X3G\n" +
                "4LG)K9W\n" +
                "Z16)YC6\n" +
                "F3S)GYV\n" +
                "5KJ)TD1\n" +
                "9B6)CG3\n" +
                "LVP)DV8\n" +
                "XQF)HYQ\n" +
                "L6V)KJ1\n" +
                "Z5V)RRS\n" +
                "T33)Y7S\n" +
                "BFP)8BZ\n" +
                "7PN)VCM\n" +
                "4VQ)R9N\n" +
                "MVG)TBF\n" +
                "QFX)GYG\n" +
                "48W)9KZ\n" +
                "CG3)5TJ\n" +
                "X8Y)1MD\n" +
                "JPT)BC4\n" +
                "Y23)K7T\n" +
                "HTL)12M\n" +
                "B5L)MVZ\n" +
                "5LF)WQ4\n" +
                "5JF)MGB\n" +
                "VHN)C5Q\n" +
                "6H2)6GB\n" +
                "ZHL)MK9\n" +
                "FVG)NLP\n" +
                "QJT)RTD\n" +
                "3KS)Q1B\n" +
                "Z32)S74\n" +
                "SR2)MKW\n" +
                "K1M)ZZ1\n" +
                "H8Z)RFW\n" +
                "2VQ)ZXH\n" +
                "PCB)SKD\n" +
                "CDW)SBY\n" +
                "ZJR)53F\n" +
                "88G)TMN\n" +
                "DF1)PQ2\n" +
                "YC7)R3K\n" +
                "QKX)D52\n" +
                "BLB)MQT\n" +
                "LR9)1S8\n" +
                "8L3)M9F\n" +
                "C79)BRF\n" +
                "HLS)8SP\n" +
                "3QH)BDD\n" +
                "K6X)XB1\n" +
                "4QD)QNY\n" +
                "NPH)1GP\n" +
                "CMQ)QKX\n" +
                "GCC)K5Y\n" +
                "N3Y)H93\n" +
                "3YK)Z4N\n" +
                "928)VYM\n" +
                "6GW)Y7R\n" +
                "NKZ)HTR\n" +
                "D7G)T8N\n" +
                "RB4)KLR\n" +
                "H6G)FH5\n" +
                "2CQ)V14\n" +
                "X8W)ZH6\n" +
                "GVG)5SK\n" +
                "TX5)XXV\n" +
                "XH1)KHR\n" +
                "MFJ)H52\n" +
                "XMF)TCD\n" +
                "X5L)5KF\n" +
                "NG8)VGL\n" +
                "KV6)DVN\n" +
                "VNF)29R\n" +
                "WSG)8CL\n" +
                "85M)ZJ8\n" +
                "7D7)2SG\n" +
                "7SR)PXF\n" +
                "K8Q)GSZ\n" +
                "G7L)Z32\n" +
                "QRW)KQK\n" +
                "98H)H87\n" +
                "9JS)P7Y\n" +
                "KYY)BZ6\n" +
                "L6N)PYC\n" +
                "MFL)34L\n" +
                "BZ4)L9V\n" +
                "9RD)5T6\n" +
                "76Z)SHM\n" +
                "D8H)QW4\n" +
                "51P)BNS\n" +
                "DTX)F87\n" +
                "DJB)Q73\n" +
                "CY9)FC1\n" +
                "843)4XK\n" +
                "K7W)N69\n" +
                "18L)9CB\n" +
                "F57)Q92\n" +
                "FCS)WSG\n" +
                "SF8)TP2\n" +
                "8BZ)31H\n" +
                "Z4Q)QT8\n" +
                "PXZ)JS9\n" +
                "JLD)3TW\n" +
                "L8S)WJ8\n" +
                "3JW)XF3\n" +
                "2NR)83X\n" +
                "DVN)4TT\n" +
                "6L7)5Y3\n" +
                "X4S)C2R\n" +
                "K6Q)PL9\n" +
                "7TF)W87\n" +
                "7ZG)S41\n" +
                "LMX)57N\n" +
                "FPQ)CSX\n" +
                "4K1)WRQ\n" +
                "3PJ)M18\n" +
                "JQM)Q9X\n" +
                "3JN)X84\n" +
                "HRL)538\n" +
                "XDL)6SX\n" +
                "6QK)L63\n" +
                "1FJ)Q5L\n" +
                "TH7)SBC\n" +
                "K8Z)J59\n" +
                "GHN)524\n" +
                "F2Y)G9G\n" +
                "9JR)HQF\n" +
                "VGF)CYT\n" +
                "DPL)K4V\n" +
                "C5Q)TNF\n" +
                "X7K)W15\n" +
                "79Y)DJB\n" +
                "56P)XPW\n" +
                "BW2)X7B\n" +
                "9L1)5KJ\n" +
                "ZCK)3J5\n" +
                "H85)SZM\n" +
                "LKN)MZJ\n" +
                "SMS)GYD\n" +
                "ZTH)MKF\n" +
                "QHT)K8W\n" +
                "CVL)JJ6\n" +
                "X2X)7ZG\n" +
                "ZTN)S1C\n" +
                "N16)G11\n" +
                "3Z9)RZY\n" +
                "19D)H9M\n" +
                "48L)YC1\n" +
                "5QL)928\n" +
                "216)CXK\n" +
                "N45)8HL\n" +
                "VT6)4HT\n" +
                "XDY)GGM\n" +
                "W8B)Y23\n" +
                "JVZ)B16\n" +
                "MHM)QMV\n" +
                "XDR)1PS\n" +
                "19W)64S\n" +
                "TXX)2HP\n" +
                "BKW)P5Q\n" +
                "9J6)11P\n" +
                "43R)V5F\n" +
                "RGB)8TK\n" +
                "6NJ)V6Q\n" +
                "ZK8)665\n" +
                "9N9)H78\n" +
                "Y77)WJL\n" +
                "VJS)YDP\n" +
                "Z5Q)3ST\n" +
                "MXF)QQ1\n" +
                "JNP)ZKM\n" +
                "R6D)LH1\n" +
                "M4B)JSP\n" +
                "Y7S)V48\n" +
                "M5V)YKJ\n" +
                "3F5)NG2\n" +
                "5PX)Q2F\n" +
                "T8N)JG3\n" +
                "83R)C7K\n" +
                "VFM)C5V\n" +
                "3J5)KYY\n" +
                "W87)NK4\n" +
                "4C2)3KS\n" +
                "ML4)PHP\n" +
                "54D)H65\n" +
                "BQP)K7W\n" +
                "N4S)9GN\n" +
                "RRP)RH1\n" +
                "C3B)D8Y\n" +
                "L74)DQM\n" +
                "XWN)916\n" +
                "NDS)ZLH\n" +
                "1PM)4FX\n" +
                "PD3)GJ5\n" +
                "F3J)L8D\n" +
                "3CM)HT5\n" +
                "GNT)2K2\n" +
                "TKF)3D5\n" +
                "2T8)RRP\n" +
                "XJN)G6R\n" +
                "VV5)74N\n" +
                "1TD)XFK\n" +
                "V9S)KMV\n" +
                "2ZM)QPV\n" +
                "C7Z)1P8\n" +
                "41H)B6T\n" +
                "GWN)HMK\n" +
                "DF4)Q8Z\n" +
                "314)XWN\n" +
                "V1B)TFW\n" +
                "1D2)2PW\n" +
                "N4P)W1P\n" +
                "WWJ)1LM\n" +
                "GF8)HWT\n" +
                "K8Z)FTB\n" +
                "MJS)TK8\n" +
                "F63)TSH\n" +
                "CWY)SCP\n" +
                "4XK)Z16\n" +
                "TBF)2KV\n" +
                "1GS)DG9\n" +
                "NBX)XKK\n" +
                "LJ2)LF4\n" +
                "WDW)M5Q\n" +
                "NTN)XT1\n" +
                "WTB)3JN\n" +
                "8N6)W1S\n" +
                "N9W)377\n" +
                "QD1)V7P\n" +
                "6HG)RSP\n" +
                "7N5)18R\n" +
                "TSG)6JN\n" +
                "SPR)7WZ\n" +
                "QHY)TDF\n" +
                "H9S)4Z9\n" +
                "4M8)X2R\n" +
                "DRJ)PP5\n" +
                "MTR)5JZ\n" +
                "8B5)4ZM\n" +
                "TJ4)6QH\n" +
                "CCR)2NX\n" +
                "SF1)MFD\n" +
                "SS1)T4M\n" +
                "VD6)5NV\n" +
                "BQ7)XZV\n" +
                "ZT7)KSV\n" +
                "97Z)4QD\n" +
                "BBP)B19\n" +
                "6JN)J94\n" +
                "R42)RQK\n" +
                "MGP)JZH\n" +
                "V9S)KNY\n" +
                "5DY)PMR\n" +
                "FK4)8HW\n" +
                "4VJ)F3J\n" +
                "J92)2NR\n" +
                "XRN)Z9K\n" +
                "M83)NP9\n" +
                "787)G49\n" +
                "N1W)ML4\n" +
                "XJD)VT6\n" +
                "7SS)9TW\n" +
                "YST)S21\n" +
                "K71)X15\n" +
                "3W4)FDC\n" +
                "1FR)GPD\n" +
                "WRW)MGT\n" +
                "TRH)K6C\n" +
                "LL2)M9H\n" +
                "NNM)XKG\n" +
                "KXX)N9V\n" +
                "5CJ)LW2");
        assert result == 358244 : "unexpected result is " + result;
        System.out.println(result);
    }

    private static int test(String s) {
        Map<String, List<String>> map = new HashMap<>();

        for (String token : s.split("\n")) {
            String[] parts = token.split("\\)");
            assert parts.length == 2 : "invalid input " + token;
            String object = parts[0];
            String orbit = parts[1];
            putRelation(map, object, orbit);
        }

        Map<String, Integer> dist = new HashMap<>();
        count(map, "COM", dist);
        int count = 0;
        for (Map.Entry<String, Integer> entry : dist.entrySet()) {
            count += entry.getValue();
        }
        return count;
    }

    private static void putRelation(Map<String, List<String>> map, String parent, String child) {
        if (map.containsKey(parent)) {
            List<String> connected = map.get(parent);
            connected.add(child);
        } else {
            List<String> connected = new ArrayList<>();
            map.put(parent, connected);
            connected.add(child);
        }
    }

    private static int count(Map<String, List<String>> map, String object,
                             Map<String, Integer> dist) {
        int count = 0;
        List<String> orbits = map.get(object);
        if (orbits != null) {
            for (String orbit : orbits) {
                count += count(map, orbit, dist) + 1;
            }
        }
        System.out.println(count + " for " + object);
        dist.put(object, count);
        return count;
    }
}
